### ISSUE TITLE
Duplicate logs for in_tail during log rotation in K8s

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3638] opened 2022-02-17 22:17 UTC
### Describe the bug

We host Fluentd in AKS(Azure Kubernetes service) and monitor the directory(/var/log/containers) for container logs. We have observed that once a file rotated, fluentd will keep reading the old one for a few seconds as expected. But read the first chunk of the new file twice or even three times. Roughly after 1 minute, it goes back to normal and no duplication any more. 

It feels like during the log rotation period, there are multiple instances reading the new file that causes data duplication. 

### To Reproduce

Copy the fluentd configuration and run in k8s environment.

### Expected behavior

No duplication.

### Your Environment

```markdown
- Fluentd version: 1.12.4
- TD Agent version:4.1.1
- Operating system:18.04.6 LTS (Bionic Beaver)
- Kernel version:5.4.0-1068-azure
```

### Your Configuration

```apache
<source>
  @type tail
  path /var/log/containers/*.log
  exclude_path ["/var/log/containers/geneva-services*.log", "/var/log/containers/prom-mdm-converter*.log"]
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  read_from_head true
  follow_inodes true
  <parse>
    # Reads logs in CRI format for Kubernetes v1.19+
    # The CRI format is documented here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md
    @type regexp
    expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
    time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
    keep_time_key true
  </parse>
</source>
```

### Your Error Log

```shell
No error log.
```

**Comment by ashie** [comment] 2022-02-18 14:28
It seems duplicate of #3464.
Please use fluentd v1.13.3 or later (td-agent 4.2.0 or later).

**Closed by ashie** 2022-02-18 14:28 UTC
