### ISSUE TITLE
docker images are broken

### ISSUE THREAD

**Issue by blbradley** [fluent/fluentd#3633] opened 2022-02-14 20:55 UTC
### Describe the bug

`fluent/fluentd-kubernetes-daemonset:v1-debian-kinesis` currently causes this error in our k8s cluster

```
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluentd (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/local/bundle/bin/fluentd:23:in `<main>'
```

broken image hash

```
sha256:bffffb5f9fb18e9e08e8934f660f9c168a648646de5b502f87a3beb3b520742b
```

last known working image hash

```
sha256:5e80b67b25d5d1457ad675f354ec0fe844e5d5088f855f80a659363ae8a03df1
```

### To Reproduce

start the image

### Expected behavior

pods should not fail

### Your Environment

```markdown
- Fluentd version:
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
- name: FLUENT_KINESIS_STREAMS_REGION
              value: us-west-2
            - name: FLUENT_KINESIS_STREAMS_STREAM_NAME
              value: kaena-gen3-lambda-logs
            - name: FLUENT_KINESIS_STREAMS_STREAM_NAME_WORDPRESS
              value: kaena-gen3-wordpress-logs-qa
            - name: FLUENT_KINESIS_STREAMS_INCLUDE_TIME_KEY
              value: 'true'
            - name: FLUENT_KINESIS_STREAMS_CHUNK_LIMIT_SIZE
              value: 1m
            - name: FLUENT_CONTAINER_TAIL_TAG
              value: kubernetes.*
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
              value: json
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
              value: json
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
```
```


### Your Error Log

```shell
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem fluentd (>= 0.a) with executable fluentd (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/local/bundle/bin/fluentd:23:in `<main>'
```
```


### Additional context

_No response_

**Comment by ashie** [comment] 2022-02-14 23:58
Duplicate of https://github.com/fluent/fluentd-kubernetes-daemonset/issues/1336

**Closed by ashie** 2022-02-14 23:58 UTC
