### ISSUE TITLE
Log missing due to file rotation

### ISSUE THREAD

**Issue by shenmuxiaosen** [fluent/fluentd#3431] opened 2021-06-23 01:07 UTC
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We are running fluentd in Kubernetes container. It is configured to tail logs under a specific directory. However, we observed that some files can lose track due to log rotation. Other files which rotate less frequent are working fine. Issue can be mitigated after restarting fluentd. 

**To Reproduce**
Trigger frequent log rotations. 

**Expected behavior**
Fluentd should properly handle the log rotation

**Your Environment**

- Fluentd or td-agent version:  flunetd v1.12.3     td-agent 4.1.1
- Operating system: Ubuntu 18.04.5
- Kernel version: 5.4.0-1047-azure

**Your Configuration**

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  tag kubernetes.*
  read_from_head true
  <parse>
    @type multi_format
    # Read logs in JSON format for Kubernetes v1.18-
    <pattern>
      format json
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      keep_time_key true
    </pattern>
    # Reads logs in CRI format for Kubernetes v1.19+
    # The CRI format is documented here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md
    <pattern>
      format regexp
      expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
      keep_time_key true
    </pattern>
  </parse>
</source>
```

**Additional context**

Is this bug somehow related with the wildcard matching for ```path```? We don't use the ```follow_inodes``` yet. I saw some discussions and hopefully tail can be more stable in v.1.13.0. But before td-agent gets released, is there a way to mitigate or walk around the issue in v1.12.3? Like with some specific configurations.

**Comment by kenhys** [comment] 2021-06-23 01:20
FYI: it may be fixed by v1.12.4. could it be reproducible with v1.12.4?
https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#bug-fix-1

> in_tail: Fix a bug that refresh_watcher fails to handle file rotations

**Comment by ashie** [comment] 2021-06-23 01:22
Please try this:

```
$ sudo td-agent-gem install fluentd --version=x.y.z
```

It seems that this issue is same with #3431 or #3365, so I close this.
If you still encounter with this issue even if v1.12.4 or later, please file a new issue.

**Closed by ashie** 2021-06-23 01:22 UTC

**Comment by shenmuxiaosen** [comment] 2021-06-23 01:54
> Please try this:
> 
> ```
> $ sudo td-agent-gem install fluentd --version=x.y.z
> ```
> 
> It seems that this issue is same with #3431 or #3365, so I close this.
> If you still encounter with this issue even if v1.12.4 or later, please file a new issue.

We have problems to use v1.12.4 or 1.13.0 as it is not available in production. Our prod image is based on td-agent.  Is there a way that we can mitigate this issue in current version?

**Comment by ashie** [comment] 2021-06-23 02:03
There is no way without replacing fluentd gem or modifying code.
We are preparing td-agent 4.2.0, it will be released until end of July at the latest.

**Comment by shenmuxiaosen** [comment] 2021-06-23 18:36
> There is no way without replacing fluentd gem or modifying code.
> We are preparing td-agent 4.2.0, it will be released until end of July at the latest.
If we upgrade to 1.12.4, do we need to change our configuration mentioned above? As we do use wildcard matching, looks like we need to enable ```follow_inodes```?

**Comment by shenmuxiaosen** [comment] 2021-06-23 18:36
> There is no way without replacing fluentd gem or modifying code.
> We are preparing td-agent 4.2.0, it will be released until end of July at the latest.

If we upgrade to 1.12.4, any changes we need to make in our existing configuration mentioned above? As we do use wildcard matching, looks like we need to enable follow_inodes?

**Comment by ashie** [comment] 2021-07-02 05:06
Probably you don't need change you config.

> looks like we need to enable follow_inodes?

It may be better to add `follow_inodes` if rotation is occurred in your log directory.
But, please note that it's very new feature since 1.12, so it might not work as expected.
