### ISSUE TITLE
Fluentd closes the connection with each message sent

### ISSUE THREAD

**Issue by cristgl** [fluent/fluentd#2642] opened 2019-10-08 19:20 UTC
Hi team!

We are trying to send thousands of messages per second to `fluentd`, but the connection gets closed each time a message is sent.
We need to have a persistent connection in order to send this amount of logs, as if we don't, the performance will be affected by the time spent in reconnecting and making the handshake with each log.

Moreover, I have been trying to understand the way Fluent Bit sends messages to `fluentd`. This is my configuration:

`fluentd` configuration file:
```
<source>
  @type         forward
  @id           secure_forward
  self_hostname myserver.local
  shared_key    secret
  secure no
</source>

<match **>
 @type stdout
</match>
```
`Fluent bit` configuration file:
```
[SERVICE]
    Flush      10
    Daemon     off
    Log_Level  info

[INPUT]
    Name       cpu
    Tag        cpu_usage

[OUTPUT]
    Name          forward
    Match         *
    Host          127.0.0.1
    Port          24224
    Shared_Key    secret
    Self_Hostname flb.local
    tls           on
    tls.verify    off
```

With that configuration and running Fluentd and Fluent bit in the same machine, the logs are not being sent, as the chunk is broken, but for each connection trial, a socket gets created:

![image](https://user-images.githubusercontent.com/14914658/66425344-3f842f00-e9c4-11e9-9d0d-c920b44fd576.png)

If I run the following command to start Fluent bit: `bin/fluent-bit -i cpu -t fluent_bit -o forward://127.0.0.1:24224`, all the messages are being sent and I can't see any new connections:

![image](https://user-images.githubusercontent.com/14914658/66425457-9853c780-e9c4-11e9-9fbd-cfd9bd52cbee.png)

Does this mean that for each message sent Fluentd closes the socket and it needs to be reopened to keep sending messages one by one as I stated before?
With this command I can also see trace messages which show new connections with a different port every time.
```
2019-10-08 12:08:51.000361779 -0700 fluent.trace: {"addr":"127.0.0.1","port":45144,"message":"[secure_forward] accepted fluent socket addr=\"127.0.0.1\" port=45144"}
```

**My environment**

- Fluentd version: v1.7.1
- Fluentbit version: v1.4.0
- Operating system:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
```
- Kernel version: 5.0.0-29-generic

Kind regards,
Cristina

**Comment by repeatedly** [comment] 2019-10-09 00:27
Does fluent-bit's out_forward keep the connection?

**Comment by ganmacs** [comment] 2019-10-09 02:50
Your fluentd's setting is wrong.
I could reproduce that fluentd and fluentd-bit establish many sockets and fluentd says `[secure_forward] incoming chunk is broken` in your setting.
The root cause is that fluent-bit sends data via TLS but  fluentd exepcts the data to be sent via not TLS.

The following is correct one.

```
<source>
  @type         forward
  @id           secure_forward

  <transport tls>
    insecure true
  </transport>

  <security>
    self_hostname myserver.local
    shared_key    secret
  </security>
</source>

<match **>
  @type stdout
</match>
```

I'll close this issue. but feel free to ask if you have any questions.

**Closed by ganmacs** 2019-10-09 02:50 UTC

**Comment by cristgl** [comment] 2019-10-09 14:20
Hi @repeatedly and @ganmacs,

Thank you for your quick answer.
I know this setting was wrong, and that I am not using the same protocol in both with those settings, this wasn't my question.
I would need to know why does fluentd close the connection each time I send a new message to it, if I am doing something wrong or it is the expected behavior. 
My main objective is to forward a large number of logs to it, but if it has to reconnect with each message sent, a lot of time is wasted. I don't know if this is the right behavior or if maybe I am doing something wrong.

Kind regards,
Cristina

**Comment by repeatedly** [comment] 2019-10-09 14:23
> Does fluent-bit's out_forward keep the connection?

Could you answer my question? > Does fluent-bit's out_forward keep the connection?

**Comment by cristgl** [comment] 2019-10-09 14:39
> bin/fluent-bit -i cpu -t fluent_bit -o forward://127.0.0.1:24224
If you mean like when I tried this command, I couldn't see any new connections with netstat (you can see the pic above), but I thought it could possibly be that this connection is quickly opened and closed and I can't get to see the port, but in the fluentd log these messages are shown:
```
2019-10-09 07:35:39.000351303 -0700 fluent.trace: {"addr":"127.0.0.1","port":60522,"message":"[secure_forward] connected fluent socket addr=\"127.0.0.1\" port=60522"}
2019-10-09 07:35:39.000398239 -0700 fluent.trace: {"addr":"127.0.0.1","port":60522,"message":"[secure_forward] accepted fluent socket addr=\"127.0.0.1\" port=60522"}
```

Note I won't use Fluent Bit to forward logs to fluentd, I just used it to understand how it worked and if it closed the socket as well as my program.

Regards,
Cristina

**Comment by ganmacs** [comment] 2019-10-10 02:50
fluentd's in_forward does **not** close the connection as @repeatedly  said(code is [here](https://github.com/fluent/fluentd/blob/02c1e2ba2e46cea5b7b77c5366dfad3a709e9ae2/lib/fluent/plugin/in_forward.rb#L212-L240)). 
The connection was closed by the client(fluentd-bit) side.

> I would need to know why does fluentd close the connection each time I send a new message to it, if I am doing something wrong or it is the expected behavior.

So the answer to this question is that the connection is closed by client side(fluent-bit) not server side(fluentd). and maybe this is the expected behavior of **fluent-bit**. 

> If you mean like when I tried this command, I couldn't see any new connections with netstat (you can see the pic above), but I thought it could possibly be that this connection is quickly opened and closed and I can't get to see the port, but in the fluentd log these messages are shown:

when fluent-bit opened and closed the connection, and opened again to send a message, it's natural that fluentd prints such a log.


Could you try fluentd's out_forward to send data and set the option [keepalive](https://docs.fluentd.org/output/forward#keepalive) to it. If you set this option, fluentd will never print like `connected fluent socket`. This means whether closing the connection or not is decided by client side(fluentd out_foward).

**Comment by ganmacs** [comment] 2019-10-11 02:37
your configuration is not correct again ...

> Could you try fluentd's out_forward to send data and set the option keepalive to it.

I said that keepalive should be added to out_forrward.
And as I said [here](https://github.com/fluent/fluentd/issues/2642#issuecomment-539798368), your config parameter about `security` looks wrong(you can see the warning log of it...).  


out_forward setting
```
<source>
  # any plugin you want
  @type dummy
  tag test
  rate 10
</source>

<match test>
  @type forward

  <server>
    host 127.0.0.1
    port 24224
  </server>

  transport tls
  tls_insecure_mode true
  keepalive true

  <security>
    self_hostname myserver.client
    shared_key    secret
  </security>
</match>
```

in_forward config
```
<source>
  @type         forward
  @id           secure_forward

  <transport tls>
    insecure true
  </transport>

  <security>
    self_hostname myserver.local
    shared_key    secret
  </security>
</source>

<match **>
  @type stdout
</match>
```

--- 

if your configutaion is exactly what you want to do, it's enough below then.

```
<source>
  # any plugin you want
  @type dummy
  tag test
  rate 10
</source>

<match test>
  @type forward

  <server>
    host 127.0.0.1
    port 24224
  </server>

  keepalive true
</match>
```


BTW if you have this kind of question next time, please post it on fluentd mailing list :)
https://github.com/fluent/fluentd/blob/02c1e2ba2e46cea5b7b77c5366dfad3a709e9ae2/CONTRIBUTING.md#got-a-question-or-problem
