### ISSUE TITLE
Certificate problems on website

### ISSUE THREAD

**Issue by nkratzke** [fluent/fluentd#4029] opened 2023-01-27 08:04 UTC
### Describe the bug

I am observing certificate problems on your website https://www.fluentd.org

Please have a look.

### To Reproduce

Open https://www.fluentd.org in a webbrowser.

### Expected behavior

Open https://www.fluentd.org in a webbrowser.

### Your Environment

```markdown
- Operating system: Mac OS
- Browser: Chrome
```

### Your Configuration

```apache
- Operating system: Mac OS
- Browser: Chrome
```

### Your Error Log

```shell
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: d.shared-425-default.ssl.fastly.net

Issuer: GlobalSign Atlas R3 DV TLS CA 2022 Q2

Expires on: 08.08.2023

Current date: 27.01.2023

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIGiDCCBXCgAwIBAgIQAc9KXFpNHjVVV1M2p32rrzANBgkqhkiG9w0BAQsFADBY
MQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEuMCwGA1UE
AxMlR2xvYmFsU2lnbiBBdGxhcyBSMyBEViBUTFMgQ0EgMjAyMiBRMjAeFw0yMjA3
MDcwNDUyMTBaFw0yMzA4MDgwNDUyMDlaMC4xLDAqBgNVBAMMI2Quc2hhcmVkLTQy
NS1kZWZhdWx0LnNzbC5mYXN0bHkubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAynuskYYWEf0CTdt8j7jtYbz2zH+V5UBiDU+DQHZuDMpeQKiB0XNV
x/ik2Twwy+n5ynVsq9W1WqMdMAhz6OmuZi9McahotzKFVn5ex9v+GF2d58/6x50t
6YnM7LhWJf7ME7A/00kVxxxckK3OJprQ8fb+B87IwV2Uz8ZBKs4WBQE2Td80SXCI
50WxEqx1y6dFnkUxS40XhFrPGPO3GGKARaCO8nYX5WaYnD7/YFZK3wrnU+OiSCeR
jsNCZn33QgQSAXABnkm1kp9egJBTVXTmI8ZDU7/mngRYLwLB3elVVnVJ4dlKIkmG
grQpfn02PaJPY2w/yzgn2b08q0P3m+QSOQIDAQABo4IDdjCCA3IwLgYDVR0RBCcw
JYIjZC5zaGFyZWQtNDI1LWRlZmF1bHQuc3NsLmZhc3RseS5uZXQwDgYDVR0PAQH/
BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQU
Ycfcn3D4Rz40j90p4wdOGrTIPPAwVwYDVR0gBFAwTjAIBgZngQwBAgEwQgYKKwYB
BAGgMgoBAzA0MDIGCCsGAQUFBwIBFiZodHRwczovL3d3dy5nbG9iYWxzaWduLmNv
bS9yZXBvc2l0b3J5LzAMBgNVHRMBAf8EAjAAMIGeBggrBgEFBQcBAQSBkTCBjjBA
BggrBgEFBQcwAYY0aHR0cDovL29jc3AuZ2xvYmFsc2lnbi5jb20vY2EvZ3NhdGxh
c3IzZHZ0bHNjYTIwMjJxMjBKBggrBgEFBQcwAoY+aHR0cDovL3NlY3VyZS5nbG9i
YWxzaWduLmNvbS9jYWNlcnQvZ3NhdGxhc3IzZHZ0bHNjYTIwMjJxMi5jcnQwHwYD
VR0jBBgwFoAUYqp0oVeg7eLE5EiYFOPT3K55USUwSAYDVR0fBEEwPzA9oDugOYY3
aHR0cDovL2NybC5nbG9iYWxzaWduLmNvbS9jYS9nc2F0bGFzcjNkdnRsc2NhMjAy
MnEyLmNybDCCAX0GCisGAQQB1nkCBAIEggFtBIIBaQFnAHYArfe++nz/EMiLnT2c
Hj4YarRnKV3PsQwkyoWGNOvcgooAAAGB1wBPjAAABAMARzBFAiBueE8AiMGgaK8h
t5AHwQyYCfhNsU5nYEDubKXQyHQHiwIhALC+r6XY5b0LUlYAmoUE4ZG+BwHOc+ct
J1RXFqCZurjHAHUAs3N3B+GEUPhjhtYFqdwRCUp5LbFnDAuH3PADDnk2pZoAAAGB
1wBQDAAABAMARjBEAiAvIHi6b1LRoKZBvFZDrDa3MV1aIwWz18NkGE7LzaZxZgIg
Y4mRzRvPtBLxdqvo7z6trInOagGWIRPR60T92wQV+8YAdgC3Pvsk35xNunXyOcW6
WPRsXfxCz3qfNcSeHQmBJe20mQAAAYHXAFAJAAAEAwBHMEUCIQCsMQV7x1ciPk2W
JLb1YdIwy/RzvBDyIeLtIAT2z5YSHgIgeTg3THve/mNSGhk2TrXf2WlNcfuOg4XF
kcrCi7ij9LkwDQYJKoZIhvcNAQELBQADggEBAGtHWZC7/9mmiute+a5OnYUCOVqr
7Qzwm1DDxCFJHs7xfE8rhUY9tmPskQwRzl2xdmtJZPby46D4tvNl1BRkgWyYcyC4
sy321Dg+lL0xgx4zqhb0+6QG6B5buBmIEfodqBw60fD5BhuUhQwGdQJokXvFpJOM
J2l9bBVBUus5ZXiMcbgKRE2ZtkbG9y4Lq5Z5oZw8oNz5Vt09b87d4vFS1Fdy+TJC
9KVj4esEcVi1jbtzniyvMkI93/kWUyKfZRqRVUl//z9aq1ZpT8UKWKA38dE+1vyw
L0tniyNr0zPo608CwgoLBgUNLUVAFqTmi4/bpEDf3UJbwv3mJRAM1fYmETU=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEjzCCA3egAwIBAgIQe55B9j2xiq6v7XsTYE8UkjANBgkqhkiG9w0BAQsFADBM
MSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMzETMBEGA1UEChMKR2xv
YmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjAeFw0yMjAxMjYxMjAwMDBaFw0y
NTAxMjYwMDAwMDBaMFgxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWdu
IG52LXNhMS4wLAYDVQQDEyVHbG9iYWxTaWduIEF0bGFzIFIzIERWIFRMUyBDQSAy
MDIyIFEyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvNQY1F/iJfnt
bzEXilBoUC+hIHTPePiWT46DmcuO6dUZ0QOu9m9DQfcQUNdq9btVW2UfwcLfkt4z
IxfqgVGQNUU3Ua+Pod4QsfaIB8MQhbcpEpunvSwEZAe5udhsorbXs0xMEPsmBDXE
qZYcGoQAPKBy03RRUgsiSmq+saJ4O1LddsnHdGJzXbj5ugi4kkVymmjzwqXFwvmE
moFcMJwj2ZHUIdwIy7s/yXiVDTC/ZfE/jqooaBJh5bM4767Ml9k6mswwvIWaZfPk
0ra8Fwz++DwZp6PqeSB9qYpnI2ww6Zvy5teoRbuPKIWvpGfM3G25vH+zEXCj7757
D6LJx9OGgQIDAQABo4IBXzCCAVswDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQG
CCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQW
BBRiqnShV6Dt4sTkSJgU49PcrnlRJTAfBgNVHSMEGDAWgBSP8Et/qC5FJK5NUPpj
move4t0bvDB7BggrBgEFBQcBAQRvMG0wLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3Nw
Mi5nbG9iYWxzaWduLmNvbS9yb290cjMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9zZWN1
cmUuZ2xvYmFsc2lnbi5jb20vY2FjZXJ0L3Jvb3QtcjMuY3J0MDYGA1UdHwQvMC0w
K6ApoCeGJWh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5jb20vcm9vdC1yMy5jcmwwIQYD
VR0gBBowGDAIBgZngQwBAgEwDAYKKwYBBAGgMgoBAzANBgkqhkiG9w0BAQsFAAOC
AQEAlHgai54B6+AFJHCaJHAnf3UqiRYu4GWSun24yqT5Kk4yeQ+HsKBK1evOL/0n
kRlIlMwnJ8oQ448aGeXmKt81WGNp1hNOh7exm6dK3LCJLp/SWlDn8CckJwMgrbhl
IcoAkI6v3hxmaX5w/74yRXWxmJ3CD66Bb8iitTJ8t0kUfoF27BezmtYoZR1iwdCe
jHX5b7fiPQ2sL6+1d+nmzwJn8SgRz3wDNLnh9VjruSv3WmCEkFGfXkQ34BWGYyNK
WCumLL0+8+IXu16B4TttpjVhFRg2m9J81NgT9gfSOUdMLCKoofK6vIg5ickX4cj4
x8rrZXQpA2/0Xn+AFLRxVuA0YA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDXzCCAkegAwIBAgILBAAAAAABIVhTCKIwDQYJKoZIhvcNAQELBQAwTDEgMB4G
A1UECxMXR2xvYmFsU2lnbiBSb290IENBIC0gUjMxEzARBgNVBAoTCkdsb2JhbFNp
Z24xEzARBgNVBAMTCkdsb2JhbFNpZ24wHhcNMDkwMzE4MTAwMDAwWhcNMjkwMzE4
MTAwMDAwWjBMMSAwHgYDVQQLExdHbG9iYWxTaWduIFJvb3QgQ0EgLSBSMzETMBEG
A1UEChMKR2xvYmFsU2lnbjETMBEGA1UEAxMKR2xvYmFsU2lnbjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMwldpB5BngiFvXAg7aEyiie/QV2EcWtiHL8
RgJDx7KKnQRfJMsuS+FggkbhUqsMgUdwbN1k0ev1LKMPgj0MK66X17YUhhB5uzsT
gHeMCOFJ0mpiLx9e+pZo34knlTifBtc+ycsmWQ1z3rDI6SYOgxXG71uL0gRgykmm
KPZpO/bLyCiR5Z2KYVc3rHQU3HTgOu5yLy6c+9C7v/U9AOEGM+iCK65TpjoWc4zd
QQ4gOsC0p6Hpsk+QLjJg6VfLuQSSaGjlOCZgdbKfd/+RFO+uIEn8rUAVSNECMWEZ
XriX7613t2Saer9fwRPvm2L7DWzgVGkWqQPabumDk3F2xmmFghcCAwEAAaNCMEAw
DgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFI/wS3+o
LkUkrk1Q+mOai97i3Ru8MA0GCSqGSIb3DQEBCwUAA4IBAQBLQNvAUKr+yAzv95ZU
RUm7lgAJQayzE4aGKAczymvmdLm6AC2upArT9fHxD4q/c2dKg8dEe3jgr25sbwMp
jjM5RcOO5LlXbKr8EpbsU8Yt5CRsuZRj+9xTaGdWPoO4zzUhw8lo/s7awlOqzJCK
6fBdRoyV3XpYKBovHd7NADdBj+1EbddTKJd+82cEHhXXipa0095MJ6RMG3NzdvQX
mcIfeg7jLQitChws/zyrVQ4PkX4268NXSb7hLi18YIvDQVETI53O9zJrlAGomecs
Mx86OyXShkDOOyyGeMlhLxS67ttVb9+E7gUJTb0o2HLO02JQZR7rkpeDMdmztcpH
WD9f
-----END CERTIFICATE-----

Certificate Transparency:

SCT Google 'Xenon2023' log (Embedded in certificate, Verified)

SCT DigiCert Nessie2023 Log (Embedded in certificate, Verified)

SCT Let's Encrypt 'Oak2023' log (Embedded in certificate, Verified)
```

**Comment by kenhys** [comment] 2023-01-27 08:10
Thank you feedback.

But it's a duplicate of https://github.com/fluent/fluentd-website/issues/250

**Closed by kenhys** 2023-01-27 08:10 UTC
