### ISSUE TITLE
The tail plugin is one position off

### ISSUE THREAD

**Issue by shihch** [fluent/fluentd#661] opened 2015-08-20 18:40 UTC
Ruby 2.2.2
Fluentd 0.12.15
Tomcat 6
Docker 1.6.1
Oraclelinux 7.1.1

Hi, I have my tomcat/app container share the volume of tomcat logs to the fluentd container.
Here is my fluentd config file:
```
<source>
  type tail
  format multiline
  format_firstline /^\[\d+-\d+-\d+\s.*\]/
  format1 /(?<message>.*)/
  path /usr/local/tomcat/logs/rcmnd.log #each log entry start with [mm-dd-yyyy hh...]
  pos_file /tmp/tomcat-multiline.pos 
  #read_from_head true
  tag app-log
</source>
<match app-log>
  type stdout
</match>
```

The fluentd send the logs to stdout fine except the newest log entry, It needs another new entry logged to show up in the fluentd stdout.

I tried to use/no use pos file make no difference. Also the out_forward plugin shows the same symptom as stdout.

**Comment by repeatedly** [comment] 2015-08-20 19:52
It is expected behaviour because fluentd can't judge this log is fully matched until find `format_firstline`.

**Comment by shihch** [comment] 2015-08-20 21:24
So you mean every time we use the tail with multiline format will have this issue? (Since fluentd would think the most recent entry is not finished yet?)  Would you please document this to your on line document? Not sure if it is possible, how about if the the newest line does not change for a couple of seconds then matcher function can match this line? Thanks!

**Comment by repeatedly** [comment] 2015-08-26 08:56
> So you mean every time we use the tail with multiline format will have this issue?

With `format_firstline`. If your multiline can be matched without `format_firstline`, in_tail emits a record immediately.

> Would you please document this to your on line document?

Sure. I will do it.

**Comment by Jorge-Rodriguez** [comment] 2015-08-31 09:59
> With format_firstline. If your multiline can be matched without format_firstline, in_tail emits a record immediately.

@repeatedly Could you explain how this works, I don't quite understand what you mean by this.

**Comment by repeatedly** [comment] 2015-08-31 15:37
@Jorge-Rodriguez For example, `format_firstline` is not needed in this example because multilines have fixed format and in_tail format matches such patterns. In this result, in_tail can emit matched logs immediately.

logs:
```
Started GET "/users/" for 127.0.0.1 at 2013-06-14 12:00:04 +0900
Processing by UsersController#index as HTML
  Rendered users/index.html.erb within layouts/application (0.5ms)
Completed 200 OK in 821ms (Views: 819.5ms | ActiveRecord: 0.0ms)


Started GET "/users/123/" for 127.0.0.1 at 2013-06-14 12:00:11 +0900
Processing by UsersController#show as HTML
  Parameters: {"user_id"=>"123"}
  Rendered users/show.html.erb within layouts/application (0.3ms)
Completed 200 OK in 4ms (Views: 3.2ms | ActiveRecord: 0.0ms)
```

```aconf
<source>
  type tail
  format multiline
  format1 /Started (?<method>[^ ]+) "(?<path>[^"]+)" for (?<host>[^ ]+) at (?<time>[^ ]+ [^ ]+ [^ ]+)\n/
  format2 /Processing by (?<controller>[^\u0023]+)\u0023(?<controller_method>[^ ]+) as (?<format>[^ ]+?)\n/
  format3 /(  Parameters: (?<parameters>[^ ]+)\n)?/
  format4 /  Rendered (?<template>[^ ]+) within (?<layout>.+) \([\d\.]+ms\)\n/
  format5 /Completed (?<code>[^ ]+) [^ ]+ in (?<runtime>[\d\.]+)ms \(Views: (?<view_runtime>[\d\.]+)ms \| ActiveRecord: (?<ar_runtime>[\d\.]+)ms\)/
  # ...
</source>
```

But this case needs `format_firstline` because multiline length is not fixed. `format_firstline` is a marker to judge multiline logs are ended or not.

```
2013-3-03 14:27:33 [main] INFO  Main - Start
2013-3-03 14:27:33 [main] ERROR Main - Exception
javax.management.RuntimeErrorException: null
    at Main.main(Main.java:16) ~[bin/:na]
2013-3-03 14:27:33 [main] INFO  Main - End
2013-3-03 14:27:33 [main] INFO  Main - Start
2013-3-03 14:27:33 [main] ERROR Main - Exception
javax.management.RuntimeErrorException: null
    at Main.main(Main.java:16) ~[bin/:na]
2013-3-03 14:27:33 [main] INFO  Main - End
```

```aconf
<source>
  type tail
  format multiline
  format_firstline /\d{4}-\d{1,2}-\d{1,2}/
  format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
  # ...
</source>
```

**Comment by repeatedly** [comment] 2015-09-01 10:37
> Would you please document this to your on line document?

I just added this to in_tail's multiline section.

**Comment by repeatedly** [comment] 2015-09-03 08:21
I close this issue.
If you want periodic flush feature, please open new issue.

**Closed by repeatedly** 2015-09-03 08:21 UTC

**Comment by Jorge-Rodriguez** [comment] 2015-09-03 11:58
@shihch I'd like the periodic feature, I've created a request on issue #668
