### ISSUE TITLE
Unexpected error Broken pipe when trying to shutdown fluentd with multiple workers

### ISSUE THREAD

**Issue by flurreN** [fluent/fluentd#3066] opened 2020-07-07 12:27 UTC
**Describe the bug**
When trying to shutdown with ctrl+c in the td-agent command promt it crashes and wont shutdown properly.

**To Reproduce**
Run config and press ctrl+c or shut in the command promt

**Expected behavior**
Should shutdown properly withouth getting stuck with errors

**Your Environment**
Windows Server 2019
fluentd 1.10.2
Tried with both td-agent 4.0.0 and 3.7.1

**Your Configuration**

```
<system>
    workers                             2
</system>

<worker 0>
    <source>
        @type                           windows_eventlog2
        @id                             windows_eventlog2_0
        read_interval                   2
        tag                             serverwindows.general
        rate_limit                      200
        channels                        x
        parse_description               true
        render_as_xml                   true
        <storage>   
            @type                       local
            persistent                  true
            path                        x
        </storage>
    </source>

    <filter serverwindows.**>
        @type                           record_transformer
        enable_ruby                     true
        <record>
            time                        ${if record["TimeCreated"] then record["TimeCreated"] end}
            fluentd_host                ${hostname}
        </record>
    </filter>

    <match serverwindows.general>
        @type                           kafka2
        brokers                         x
        username                        x
        password                        x
        scram_mechanism                 x
        ssl_ca_cert                     x
        default_topic                   x

        <format>
            @type                       json
        </format>

        <buffer>
            @type                       file
            path                        x
            flush_mode                  interval
            flush_interval              2s
            flush_thread_count          8
            retry_wait                  5s
            chunk_limit_size            5m
            flush_at_shutdown           true
        </buffer>
    </match>

</worker>

<worker 1>
    <source>
        @type                           windows_eventlog2
        @id                             windows_eventlog2_1
        read_interval                   2
        tag                             serverwindows.security
        rate_limit                      200
        channels                        x
        parse_description               true
        render_as_xml                   true
        <storage>
            @type                       local
            persistent                  true
            path                        x
        </storage>
    </source>
	
    <filter serverwindows.**>
        @type                           record_transformer
        enable_ruby                     true
        <record>
            time                        ${if record["TimeCreated"] then record["TimeCreated"] end}
            fluentd_host                ${hostname}

        </record>
    </filter>

    <match serverwindows.security>
        @type                           kafka2
        brokers                         x
        username                        x
        password                        x
        scram_mechanism                 x
        ssl_ca_cert                     x
        default_topic                   x

        <format>
        	@type                       json
        </format>

        <buffer>
            @type                       file
            path                        x
            flush_mode                  interval
            flush_interval              2s
            flush_thread_count          8
            retry_wait                  5s
            chunk_limit_size            5m
            flush_at_shutdown           true
        </buffer>
    </match>
</worker>
```

**Your Error Log**

```
2020-07-07 13:08:04 +0200 [info]: #1 fluentd worker is now running worker=1
2020-07-07 13:08:04 +0200 [info]: #0 fluentd worker is now running worker=0
2020-07-07 13:08:30 +0200 [info]: Received graceful stop
2020-07-07 13:08:30 +0200 [info]: #1 fluentd worker is now stopping worker=1
2020-07-07 13:08:30 +0200 [info]: #1 shutting down fluentd worker worker=1
2020-07-07 13:08:30 +0200 [info]: #1 shutting down input plugin type=:windows_eventlog2 plugin_id="windows_eventlog2_1"
2020-07-07 13:08:30 +0200 [info]: #1 shutting down output plugin type=:kafka2 plugin_id="object:2b15510"
2020-07-07 13:08:30 +0200 [info]: #1 shutting down filter plugin type=:record_transformer plugin_id="object:21a7410"
2020-07-07 13:08:30 +0200 [info]: Worker 1 finished with status 0
Unexpected error Broken pipe
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
Unexpected error Broken pipe
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
Unexpected error Broken pipe
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
Unexpected error Broken pipe
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'

```
After the first ctrl+c it stops at `2020-07-07 13:08:30 +0200 [info]: Worker 1 finished with status 0` and then for every  ctrl+c it gives the `Unexpected error Broken pipe`. If I wait after the first ctrl+c it nothing will happenes.

It works fine when restarting and shuting it down via services.

**Comment by kenhys** [comment] 2020-10-21 02:31
I could reproduce it with td-agent 4.0.1 (simple .conf), too.


Windows 10 (Pro) 2004 (19041.572)
td-agent 4.0.1 http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.0.1-x64.msi
(bundled fluentd 1.11.2)

Here is the sample:

```
<system>
  workers 2
</system>

<worker 0>
  <source>
    @type sample
    @id sample1
    sample {"worker1":"hello worker 1"}
    auto_increment_key count
    rate 1
    tag sample1
  </source>
  <match sample1>
    @type file
    path sample1.log
  </match>
</worker>

<worker 1>
  <source>
    @type sample
    @id sample2
    sample {"worker1":"hello worker 2"}
    auto_increment_key count
    rate 1
    tag sample2
  </source>
  <match sample2>
    @type file
    path sample2.log
  </match>
</worker>
```


```
2020-10-21 11:24:31 +0900 [info]: starting fluentd-1.11.2 pid=1628 ruby="2.7.1"
2020-10-21 11:24:31 +0900 [info]: spawn command to main:  cmdline=["C:/opt/td-agent/bin/ruby.exe", "-Eascii-8bit:ascii-8bit", "C:/opt/td-agent/bin/fluentd", "-c", ".\\multiworker.conf", "--under-supervisor"]
2020-10-21 11:24:38 +0900 [info]: #0 adding match pattern="sample1" type="file"
2020-10-21 11:24:38 +0900 [info]: #1 adding match pattern="sample2" type="file"
2020-10-21 11:24:38 +0900 [info]: #0 adding source type="sample"
2020-10-21 11:24:38 +0900 [info]: #1 adding source type="sample"
2020-10-21 11:24:38 +0900 [warn]: #0 [sample1] both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-10-21 11:24:38 +0900 [warn]: #0 [sample1] both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-10-21 11:24:38 +0900 [info]: #0 starting fluentd worker pid=8516 ppid=1628 worker=0
2020-10-21 11:24:38 +0900 [info]: #0 fluentd worker is now running worker=0
2020-10-21 11:24:38 +0900 [warn]: #1 [sample2] both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-10-21 11:24:38 +0900 [warn]: #1 [sample2] both of Plugin @id and path for <storage> are not specified. Using on-memory store.
2020-10-21 11:24:38 +0900 [info]: #1 starting fluentd worker pid=6024 ppid=1628 worker=1
2020-10-21 11:24:38 +0900 [info]: #1 fluentd worker is now running worker=1
2020-10-21 11:24:41 +0900 [info]: Received graceful stop
2020-10-21 11:24:41 +0900 [info]: #1 fluentd worker is now stopping worker=1
2020-10-21 11:24:41 +0900 [info]: #1 shutting down fluentd worker worker=1
2020-10-21 11:24:41 +0900 [info]: #1 shutting down input plugin type=:sample plugin_id="sample2"
2020-10-21 11:24:41 +0900 [info]: #1 shutting down output plugin type=:file plugin_id="object:9ec"
2020-10-21 11:24:42 +0900 [info]: Worker 1 finished with status 0
Unexpected error Broken pipe
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
Unexpected error Broken pipe
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
Unexpected error Broken pipe
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `write'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/multi_spawn_server.rb:51:in `stop'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/server.rb:104:in `block (2 levels) in install_signal_handlers'
  C:/opt/td-agent/lib/ruby/gems/2.7.0/gems/serverengine-2.2.1/lib/serverengine/signal_thread.rb:96:in `main'
```

Ctrl+C doesn't work as expected.

![Peek 2020-10-21 11-30](https://user-images.githubusercontent.com/225841/96665891-e4379b80-1390-11eb-938d-81b28e46a230.gif)

**Comment by ashie** [comment] 2020-10-22 00:26
It also reproduce with #3131.

When I implemented #3131, I suspected that the current implementation doesn't seem support multiple workers:

https://github.com/treasure-data/serverengine/blob/66b3deb23eaaa2e5d7f59c3498dbf6d231e0ca2b/lib/serverengine/multi_spawn_server.rb#L51

but I didn't confirmed it until I've found this issue now.

**Comment by ashie** [comment] 2020-10-26 06:51
The cause is that ServerEngine holds only last worker's pipe and discards others.
Following quick patch solves this problem.

```diff
diff --git a/lib/serverengine/multi_spawn_server.rb b/lib/serverengine/multi_spawn_server.rb
index 7210d20..f45a37f 100644
--- a/lib/serverengine/multi_spawn_server.rb
+++ b/lib/serverengine/multi_spawn_server.rb
@@ -48,7 +48,9 @@ module ServerEngine
 
     def stop(stop_graceful)
       if @command_sender == "pipe"
-        @pm.command_sender_pipe.write(stop_graceful ? "GRACEFUL_STOP\n" : "IMMEDIATE_STOP\n")
+        @pm.command_sender_pipes.each do |pipe|
+          pipe.write(stop_graceful ? "GRACEFUL_STOP\n" : "IMMEDIATE_STOP\n")
+        end
       end
       super
     end
diff --git a/lib/serverengine/process_manager.rb b/lib/serverengine/process_manager.rb
index 418f2a7..afab575 100644
--- a/lib/serverengine/process_manager.rb
+++ b/lib/serverengine/process_manager.rb
@@ -71,7 +71,7 @@ module ServerEngine
     attr_reader :enable_heartbeat, :auto_heartbeat
 
     attr_accessor :command_sender
-    attr_reader :command_sender_pipe
+    attr_reader :command_sender_pipes
 
     CONFIG_PARAMS = {
       heartbeat_interval: 1,
@@ -181,9 +181,10 @@ module ServerEngine
         end
 
         if @command_sender == "pipe"
-          inpipe, @command_sender_pipe = IO.pipe
-          @command_sender_pipe.sync = true
-          @command_sender_pipe.binmode
+          inpipe, pipe = IO.pipe
+          pipe.sync = true
+          pipe.binmode
+          @command_sender_pipes << pipe
           options[:in] = inpipe
         end
         env['SERVERENGINE_SOCKETMANAGER_INTERNAL_TOKEN'] = SocketManager::INTERNAL_TOKEN
```

But I think it's not enough. Some other similar codes should be fixed too, and probably command sender should be moved to Monitor class.

**Comment by ashie** [comment] 2020-11-11 06:25
Fixed in https://github.com/treasure-data/serverengine/pull/105

**Closed by ashie** 2020-11-11 06:25 UTC
Labels: bug
