### ISSUE TITLE
handle log file read permission error for in_tail

### ISSUE THREAD

**Issue by larsf** [fluent/fluentd#936] opened 2016-05-06 19:58 UTC
Currently, in_tail rescues the event raised when fluentd tries to open a non existent log file. Can we please have it handle ENOPERM the same way so fluentd doesn't continuously barf on it

Fluentd's log file filled with:
2016-05-06 10:00:24 -0700 [error]: Permission denied @ rb_sysopen - /var/log/messages
2016-05-06 10:00:24 -0700 [error]: suppressed same stacktrace

rescue Errno::ENOENT is the relevant line

**Comment by repeatedly** [comment] 2016-05-06 20:11
> Currently, in_tail rescues the event raised when fluentd tries to open a non existent log file

From your logs, the problem is not non-existent file. You should add right permission to your file for fluentd.

**Comment by larsf** [comment] 2016-05-06 20:18
I would like fluentd to issue one warning for a file it has no permissions to, and go on, just like it it ignores files that it cannot find.

**Comment by repeatedly** [comment] 2016-05-06 20:25
Similar to https://github.com/fluent/fluentd/issues/903 ?

**Comment by larsf** [comment] 2016-05-06 20:28
Yes similar. Fluentd behaves very nicely when it encounter a log file it cannot find, I would like to see it do the same for a log file it cannot read - issue one warning and ignore that log file until next restart.

**Comment by repeatedly** [comment] 2016-05-09 00:58
Can we merge this issue into #903?

**Comment by ashie** [comment] 2021-07-30 07:23
Fixed by #3378 and #3477

**Closed by ashie** 2021-07-30 07:23 UTC
Labels: enhancement
