### ISSUE TITLE
system configuration to have logs in json format not applied on log file created message in fluentd logs.

### ISSUE THREAD

**Issue by pratikshavyas** [fluent/fluentd#4011] opened 2023-01-17 05:31 UTC
### Describe the bug

I have enabled log rotation for fluentd and also added system configuration to have fluentd's own logs in JSON format.

```aconf
<system>
    <log>
        format json
        time_format %Y-%m-%dT%H:%M:%S%z
    </log>
</system>
```

However, I see that below fluentd log, still does not come in JSON format:
"# Logfile created on 2023-01-13 03:14:26 -0500 by logger.rb/v1.4.2"

Is this expected that this log will not come in JSON format or is there anything else required in the config.

### To Reproduce

Enable log rotation in fluentd and redirect fluentd logs to a file

### Expected behavior

 Logfile created on 2023-01-13 03:14:26 -0500 by logger.rb/v1.4.2  --> This log should also follow JSON format as system config should get applied on all fluentd logs.

### Your Environment

```markdown
- Fluentd version: 1.14.6
- TD Agent version: 4.3.1
```

### Your Configuration

```apache
<system>
    <log>
        format json
        time_format %Y-%m-%dT%H:%M:%S%z
    </log>
</system>
```

### Your Error Log

```shell
{"log":{"message":"pattern not matched: \"# Logfile created on 2023-01-16 21:16:43 -0500 by logger.rb/v1.4.2\""}}
```

**Comment by daipom** [comment] 2023-02-03 10:33
This could be the bug of the fix: a7771835d65dea8e49d284a148d94cecb1abed19, but this fix is included in v1.15.3.

I'm checking ...

**Comment by daipom** [comment] 2023-02-06 08:35
> However, I see that below fluentd log, still does not come in JSON format:
> "# Logfile created on 2023-01-13 03:14:26 -0500 by logger.rb/v1.4.2"

This seems to be caused by the [Logger](https://github.com/ruby/logger) library.
Fluentd uses the library, and it outputs such comments when it rotates the log files.

I think this is just a comment, not a log, so this line should be ignored.

@pratikshavyas Do you have some system reading the log files of Fluentd?
If so, please consider using the [capture-fluentd-logs](https://docs.fluentd.org/deployment/logging#capture-fluentd-logs) feature.
If you have a reason not to use this feature, please exclude this comment line beginning with `#`.

Or perhaps it can be modified so that it does not output this comment line.

**Comment by daipom** [comment] 2023-02-15 04:23
I close this, but please reopen this if there is something we need.

**Closed by daipom** 2023-02-15 04:23 UTC
Labels: waiting-for-user
