### ISSUE TITLE
in_tail fails to detect file rotation with log4 logs

### ISSUE THREAD

**Issue by katriel** [fluent/fluentd#544] opened 2015-01-28 16:40 UTC
I'm seeing this behavior with log files created with log4j. Rotation is detected sometimes 20-30 minutes after the actual file rotation. Rotation happens every hour.

Running fluentd 0.12.4 installed from gem with ruby 2.1

###### From fluent.log:
2015-01-28 14:34:25 +0200 [info]: detected rotation of /var/log/server/server.log; waiting 5 seconds
2015-01-28 14:34:25 +0200 [info]: following tail of /var/log/server/server.log
2015-01-28 15:42:36 +0200 [info]: detected rotation of /var/log/server/server.log; waiting 5 seconds
2015-01-28 15:42:36 +0200 [info]: following tail of /var/log/server/server.log
2015-01-28 17:09:30 +0200 [info]: detected rotation of /var/log/server/server.log; waiting 5 seconds
2015-01-28 17:09:30 +0200 [info]: following tail of /var/log/server/server.log

###### lsof
lsof shows fluent holding all the rotated file handlers. The previous file (/var/log/server/server.log.2015-01-28-17) is held twice:
$ lsof -n | grep server/server.log
fluentd    4725    fluentd   31u      REG                9,0 6989675986    3145756 /var/log/server/server.log.2015-01-28-17
fluentd    4725    fluentd   32r      REG                9,0 6989675986    3145756 /var/log/server/server.log.2015-01-28-17
fluentd    4725    fluentd   38r      REG                9,0 5032834348    3145970 /var/log/server/server.log.2015-01-28-08
fluentd    4725    fluentd   40r      REG                9,0 4424197667    3146026 /var/log/server/server.log.2015-01-28-12
fluentd    4725    fluentd   41r      REG                9,0 4548295792    3145977 /var/log/server/server.log.2015-01-28-09
fluentd    4725    fluentd   42r      REG                9,0 4386869199    3145992 /var/log/server/server.log.2015-01-28-10
fluentd    4725    fluentd   44r      REG                9,0 4326276642    3146012 /var/log/server/server.log.2015-01-28-11
fluentd    4725    fluentd   45r      REG                9,0 5918476136    3146068 /var/log/server/server.log.2015-01-28-15
fluentd    4725    fluentd   46r      REG                9,0 4520370894    3146040 /var/log/server/server.log.2015-01-28-13
fluentd    4725    fluentd   47r      REG                9,0 4748760626    3146054 /var/log/server/server.log.2015-01-28-14
java       4968    tomcat6   42u      REG                9,0 2526929547    3145760 /var/log/server/server.log

###### Source configuration
```
<source>
  type tail
  format multiline
  # Match the date at the beginning of each entry, which can be in one of two
  # different formats.
  format_firstline /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) \[(?<thread>[^ ]*)\]/
  format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) \[(?<thread>[^ ]*)\] \[(?<user>[^ ]*[ ]?)\] (?<level>[^\s]+)(?<message>.*)/
  path /var/log/server/server.log
  pos_file /var/tmp/fluentd.server.pos
  read_from_head true
  tag server
</source>
```

**Comment by repeatedly** [comment] 2015-01-28 18:46
Could you explain the log4j's behaviour?
I can't judge this is the bug of in_tail or log4j file handling causes this result.

**Comment by katriel** [comment] 2015-01-29 08:08
Log4j uses a RollingFileAppender configure to start a new file every hour:

log4j.appender.P=org.apache.log4j.DailyRollingFileAppender
log4j.appender.P.File=/var/log/server/server.log
log4j.appender.P.DatePattern='.'yyyy-MM-dd-HH

To make sure the file has a new inode, I ran "stat" on both rotated and new fie, as you can see, they have a different inodes:
# stat server.log
  File: `server.log'
  Size: 177958023 	Blocks: 347576     IO Block: 4096   regular file
Device: 900h/2304d	Inode: 7602454     Links: 1

# stat server.log.2015-01-29-09
  File: `server.log.2015-01-29-09'
  Size: 5735579945	Blocks: 11202320   IO Block: 4096   regular file
Device: 900h/2304d	Inode: 7602439     Links: 1

Mean while, rotation is not detected.

**Comment by repeatedly** [comment] 2015-01-29 23:41
Could you show me reproducible sample code and the procedure?
I'm not familiar with log4j so I want correct test set to debug this problem.

**Comment by katriel** [comment] 2015-02-02 13:12
Download log4j 1.2.17 from http://central.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
Compile like so:
```
$ javac -cp ./:log4j-1.2.17.jar Issue554.java
```

To run:
```
java -cp ./:log4j-1.2.17.jar Issue554 <threads> <log interval>
```

I was able to recreate the problem when using 30 threads at 10ms interval. Running on EC2, 8 cores, 15G of RAM.
```
java -cp ./:log4j-1.2.17.jar Issue554 30 10
```

Issue554.java:
```java
import java.io.IOException;
import org.apache.log4j.Logger;

class MyRunnable implements Runnable {
    private Logger logger=null;
    private int sleepInterval;

    public MyRunnable(int sleepInterval) {
        logger = Logger.getLogger(Issue554.class.getName());
        this.sleepInterval = sleepInterval;
    }

    public void run() {
        while (true) {
                for(int i=0;i<30;i++) {
                    logger.warn("The quick brown fox jumps over the lazy dog The quick brown fox jumps over the lazy dog");
                }
            try {
                Thread.sleep(this.sleepInterval);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}


public class Issue554 {

    public static void main(String[] args) throws IOException {
        int threads = Integer.parseInt(args[0]);
        int sleepInterval = Integer.parseInt(args[1]);
        System.out.println("Logging from " + Integer.toString(threads) + " threads, in intervals of " + Integer.toString(sleepInterval) + "ms");

        Thread[] worker=new Thread[threads];
        MyRunnable r = new MyRunnable(sleepInterval);

        for(int i=0;i<threads;i++) {
            worker[i]=new Thread(r);
            worker[i].start();
        }
    }
}
```

fluentd.conf
```
<source>
  type tail
  format multiline
  format_firstline /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) \[(?<thread>[^ ]*)\]/
  format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) \[(?<thread>[^ ]*)\] \[(?<user>[^ ]*[ ]?)\] (?<level>[^\s]+)(?<message>.*)/
  #format2 /(?<message>.*)/
  path ./server.log
  pos_file /tmp/fluentd.server.pos
  read_from_head true
  tag server
</source>

<match **>
    type null
</match>
```

log4j.properties
```
log4j.rootLogger=WARN, R

log4j.appender.R=org.apache.log4j.DailyRollingFileAppender
log4j.appender.R.File=./server.log
log4j.appender.R.DatePattern='.'yyyy-MM-dd-HH-mm
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d [%t] [%x] %-5p %c - %m%n
```

**Comment by katriel** [comment] 2015-02-02 13:14
Feel free to replace any occurrence of 554 with 544 :-)

Log rotation is set to happen every minute, instead of every hour, but the symptoms are identical.

**Comment by repeatedly** [comment] 2015-02-02 16:08
Thank you!
I will check it later.

From this thread, log4j may have weird behaviour so
we should check log4j's rotation mechanizm.

https://groups.google.com/forum/#!topic/fluentd/oSKisjw-RmQ

**Comment by katriel** [comment] 2015-02-08 07:41
For reference, log4j's DailyRollingFileAppender's rollOver is defined at
http://svn.apache.org/viewvc/logging/log4j/tags/v1_2_17/src/main/java/org/apache/log4j/DailyRollingFileAppender.java?revision=1342873&view=markup
Line 303

**Comment by AlexGaspar** [comment] 2015-02-09 10:04
Same issue here, it fails detecting the rotation of /var/log/syslog, which is populated by Marathon [(It also uses log4j)](https://github.com/mesosphere/marathon/search?utf8=%E2%9C%93&q=log4j)

**Comment by repeatedly** [comment] 2015-02-10 02:36
From log4j implementation, log4j doesn't lock the mutex before file rotation.
And log4j doc said `DailyRollingFileAppender has been observed to exhibit synchronization issues and data loss.`
We should not use DailyRollingFileAppender and in_tail can't handle this problem.
Maybe application should create one thread to log message for making log4j thread safety.

**Comment by repeatedly** [comment] 2015-02-13 07:14
I close this issue because this is DailyRollingFileAppender problem and handing in in_tail is toooooo hard.
If someone hits similar problem with thread-safety appender, please re-open this issue.

**Closed by repeatedly** 2015-02-13 07:14 UTC

**Comment by redbaron** [comment] 2016-03-30 16:28
We see same issue and I can't see how it is log4j fault. Problem lies withing `in_tail` plugin, which breaks if file is rotated within `rotate_wait` seconds more than once. The fact that log4j does it due to it's own problems is irrelevant and shouldn't make fluentd to misbehave. 

Here is reproducible test-case which doesn't involve log4j at all, just basic shell scripts: https://gist.github.com/redbaron/645f9f8ace77d04aabd9

Output on my machine looks like following:
```
Started container 9a5e80002d803e14ca1bb014ef8bae66716d9e86c52e331345ae91d37e92fb38
Generating logs
Comparing results
original output: 100000
fluent produced: 512152
fluent produced: 558305
fluent produced: 604218
fluent produced: 651155
fluent produced: 698333
fluent produced: 744246
fluent produced: 790159
fluent produced: 836313
fluent produced: 880177
fluent produced: 923259
fluent produced: 964291
fluent produced: 970195
```

**Comment by repeatedly** [comment] 2016-04-01 17:36
@redbaron Not a bug. `rotate_wait` should be smaller than rotation interval.
If you set `rotate_wait 2s` and `sleep 5` in your `run.sh`, problem doesn't happen.

**Comment by redbaron** [comment] 2016-04-04 09:43
@repeatedly you are not telling me anything new, apart from that it is not a bug:

> breaks if file is rotated within rotate_wait seconds more than once

 Any robust system must have size based rotation policy, otherwise many bad things can happen. When unfortunate happen occurs, despite having problems with the service itself (obviously under normal condition it wont spam in logs), we are have 2 problems on our hands - misbehaving fluentd is added on top. How come log handling daemon breaking apart when there is a problem with service is a can be though of something normal? 

Logs are most important exactly when there are problems with the service and anything which goes around them should at least try to be 100% correct.

**Comment by repeatedly** [comment] 2016-04-05 21:27
> How come log handling daemon breaking apart when there is a problem with service is a can be though of something normal?

Could you tell me more detailed explanation?
in_tail seems to handle your case with proper configuration.
What should fluentd care?

**Comment by richm** [comment] 2016-05-03 14:24
Assuming log rotation uses a mv or rename() within the same file system, in_tail could keep track of the inode number, and would know that the file with new name "main.log.2" is the same as the file with the old name "main.log" because they have the same inode number.  Then in_tail could ignore main.log.2 or mark it as already read.

**Comment by richm** [comment] 2016-05-04 20:04
It works much better if the file that you specify to tail exists before fluentd starts.  I don't follow all of the logic in in_tail.rb, but it seems that if the file doesn't exist at the start, it waits until the rotation (or ??? some other criteria) until it starts reading from the file.  I also used `rotate_wait 30` so fluentd could continue reading from the rotated file in case it was buffered, `enable_watch_timer false`, `read_from_head  true`, and `refresh_interval 1`.
