### ISSUE TITLE
multiline Example in tail Input Plugin Documentation

### ISSUE THREAD

**Issue by Git-Rajkumar** [fluent/fluentd#1513] opened 2017-03-22 05:39 UTC
I need to know  multiline Example in tail Input Plugin [Documentation](docs.fluentd.org/v0.12/articles/in_tail#multilineflushinterval) is right?

I tried to parse Java like stacktrace logs with multiline. Here is a configuration example. in tail Input Plugin Documentation

**Documentation format:**

         format multiline
         format_firstline /\d{4}-\d{1,2}-\d{1,2}/
	     format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/

**Documentation Log Example:**

    2013-3-03 14:27:33 [main] INFO  Main - Start
	2013-3-03 14:27:33 [main] ERROR Main - Exception
	javax.management.RuntimeErrorException: null
	    at Main.main(Main.java:16) ~[bin/:na]
	2013-3-03 14:27:33 [main] INFO  Main - End

**Docuementation Output:**

     2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - Start"}
	2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"ERROR","message":" Main - Exception\njavax.management.RuntimeErrorException: null\n    at Main.main(Main.java:16) ~[bin/:na]"}
	2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - End"}

When Try check this example: exact format then throw below error:

     /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.52/lib/fluent/config/basic_parser.rb:81:in `parse_error!': unexpected back-slash escape character 'd' at td-agent.conf line 83,22 (Fluent::ConfigParseError)
	 82:   format multiline
	 83:   format_firstline /\d{4}-\d{1,2}-\d{1,2}/

After follow this [link](https://github.com/fluent/fluentd/issues/313) to add \ to all character then throw **pattern not match error.**

Like:

**My Changed td-agent Configuration:**

	<source>
	  type tail
	  format multiline
	  format_firstline /\\d{4}-\\d{1,2}-\\d{1,2}/
	  format1 /^(?<time>\\d{4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2}) \[(?<thread>.*)\] (?<level>[^\\s]+)(?<message>.*)/
	  tag apache.access
	  path /var/log/testing.log  //documentation log path
	</source>

	<match apache.access>
	  type stdout
	</match>

**Error:**

      2017-03-22 10:44:23 +0530 [warn]: pattern not match: "2013-3-03 14:27:33 [main] INFO  Main - Start"
      2017-03-22 10:44:23 +0530 [warn]: pattern not match: "2013-3-03 14:27:33 [main] ERROR Main - Exception\njavax.management.RuntimeErrorException: null\n    at Main.main(Main.java:16) ~[bin/:na]"

The Configuration file throw **pattern not match** error suggest me what i miss in this Configuration or multiline Example in tail Input Plugin Documentation is right?

I am working on this issue  https://github.com/fluent/fluentd/issues/1511, suggest me same type of issue. how to fix this.

**Comment by repeatedly** [comment] 2017-03-31 07:47
Fluentd v0.10 is EOL.
Could you try above configuration with v0.12 or later?

**Comment by drywheat** [comment] 2018-03-23 14:47
I can confirm the same behavior using Fluentd v1.1.2.

**Comment by okkez** [comment] 2018-04-05 04:13
I could not reproduce the situation with following configuration and Fluentd v1.1.2.

```
<source>
  @type tail
  <parse>
    @type multiline
    format_firstline /\d{4}-\d{1,2}-\d{1,2}/
    format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
  </parse>
  # format multiline
  # format_firstline /\d{4}-\d{1,2}-\d{1,2}/
  # format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) \[(?<thread>.*)\] (?<level>[^\s]+)(?<message>.*)/
  multiline_flush_interval 3s
  path local/1513.log
  pos_file local/1513.pos
  read_from_head true
  tag test
</source>

<match test>
  @type stdout
</match>
```

**Comment by okkez** [comment] 2018-12-06 07:10
I could not reproduce the situation with Fluentd v1.3.1. Closing.

If this issue is reproducible with latest Fluentd, feel free to create a new issue.

**Closed by okkez** 2018-12-06 07:10 UTC
Labels: incomplete
