### ISSUE TITLE
`bundle exec rake test` requires git command in Windows-systems PATH

### ISSUE THREAD

**Issue by reversi-fun** [fluent/fluentd#1403] opened 2017-01-06 01:23 UTC
- fluentd  version:fluentd-0.14.11-x86-mingw32
- Environment information:Windows 7 x64
- configuration:
  ruby 2.2.5 and gems required by fluentd.
- problem explanation;
when run  "fluentd\test\test_supervisor.rb" , then 2 errors caused.
>>
cd  fluentd\test
ruby test_supervisor.rb
>>
>> log is there
Error: test_load_config_for_daemonize(SupervisorTest): Errno::ENOENT: No such file or directory @ rb_sysopen - test/tmp/supervisor/log
..rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11-x86-mingw32/lib/fluent/supervisor.rb:329:in `initialize'
..rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11-x86-mingw32/lib/fluent/supervisor.rb:329:in `open'
../rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11-x86-mingw32/lib/fluent/supervisor.rb:329:in `init'
..rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11-x86-mingw32/lib/fluent/supervisor.rb:251:in `load_config'
test_supervisor.rb:269:in `block in test_load_config_for_daemonize'
     266:     params['suppress_repeated_stacktrace'] = true
     267:     params['log_level'] = Fluent::Log::LEVEL_INFO
     268:     params['daemonize'] = './fluentd.pid'
  => 269:     load_config_proc =  Proc.new { Fluent::Supervisor.load_config(tmp_dir, params) }
     270:
     271:     # first call
     272:     se_config = load_config_proc.call
test_supervisor.rb:272:in `call'
test_supervisor.rb:272:in `test_load_config_for_daemonize'
>>
================================================================

**Comment by repeatedly** [comment] 2017-01-06 02:11
This doesn't happen when `bundle exec rake test`, right?

**Comment by reversi-fun** [comment] 2017-01-06 03:15
yes. 
when "bundle exec rake test" then it cause other error.
May be Gemfile is Incorrect on Windows.
>>
gem list
...
oj (2.18.0)
>>

>>
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `fluentd.gemspec`: No such file or director
y - git ls-files. Bundler cannot continue.

 #  from I:/kibana/fluentd/fluentd.gemspec:13
 #  -------------------------------------------
 #    gem.add_development_dependency("oj", ["~> 2.14"])
 >  end
 #  require File.expand_path('../lib/fluent/version', __FILE__)
 #  -------------------------------------------
. Bundler cannot continue.

 #  from I:/kibana/fluentd/Gemfile:3
 #  -------------------------------------------
 #    instance_eval File.read(local_gemfile)
 >  end
 #  source 'https://rubygems.org/'
 #  -------------------------------------------
>>

**Comment by repeatedly** [comment] 2017-01-06 03:22
I'm not sure how to setup your fluentd but tests passed on AppVeyor's windows: https://ci.appveyor.com/project/fluent/fluentd/build/2065
So if `bundle exec rake test` failed, your environment is something wrong.
I will check why single file test fails later.

**Comment by repeatedly** [comment] 2017-01-06 03:23
This is low priority because the problem is test code, not fluentd itself.

**Comment by reversi-fun** [comment] 2017-01-06 03:28
>I will check why single file test fails later.
I see "low priority ".
Best reguards.

**Comment by reversi-fun** [comment] 2017-01-06 04:59
I corrected the environment and made `bundle exec rake test ` successful.
but　The problem of   "fluentd\test\test_supervisor.rb"  has been reproduced .

--What has changed
--- Previous environment
I added git to the environment variable path after entering the DOS prompt.
then "`git ls-files`.split($\)" outputs ”No such file or directory".

--- current environment
I added git to the environment variable path before entering the DOS prompt by Windows SYSTEMS COMPUTERS properties.
then sucess `bundle exec rake test`.

I also add Japanese to make up for broken English.
Rubyのバッククオート（‘‘）によるコマンド起動パスは、環境変数のPATHの設定方法によって”No such file or directory"エラーとなる。
DOSプロンプトに入ってからPATHに追加したコマンドは、バッククオート（‘‘）で起動できない。
DOSプロンプトに入る前に、Windowsシステムの詳細設定画面の”コンピュータプロパティ”の設定で、PATHに追加したコマンドは、バッククオートで起動できた。

>> `bundle exec rake test `
2144 tests, 9477 assertions, 0 failures, 0 errors, 0 pendings, 12 omissions, 0 n
otifications
100% passed
>>
>>
 Error: test_load_config(SupervisorTest): Errno::ENOENT: No such file or director
y @ rb_sysopen - I:/kibana/fluentd/test/test/tmp/supervisor/log
/rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11
-x86-mingw32/lib/fluent/supervisor.rb:329:in `initialize'
/rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11
-x86-mingw32/lib/fluent/supervisor.rb:329:in `open'
rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11
-x86-mingw32/lib/fluent/supervisor.rb:329:in `init'
rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11
-x86-mingw32/lib/fluent/supervisor.rb:251:in `load_config'
test_supervisor.rb:204:in `block in test_load_config'
     201:     params['log_path'] = 'test/tmp/supervisor/log'
     202:     params['suppress_repeated_stacktrace'] = true
     203:     params['log_level'] = Fluent::Log::LEVEL_INFO
  => 204:     load_config_proc =  Proc.new { Fluent::Supervisor.load_config(tmp_
dir, params) }
     205:
     206:     # first call
     207:     se_config = load_config_proc.call
test_supervisor.rb:207:in `call'
test_supervisor.rb:207:in `test_load_config'
--------------------------------------------------------------------------------

13 tests, 47 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifi
cations
84.6154% passed
--------------------------------------------------------------------------------
>>

**Comment by tagomoris** [comment] 2017-01-06 06:00
Is it a bug should be fixed?
This requirement is very common one in ruby projects, so I want to add this requirement for developers.

**Comment by reversi-fun** [comment] 2017-01-06 07:06
My original issue is about "fluentd\test\test_supervisor.rb" .
Errno::ENOENT: No such file or directory @ rb_sysopen - test/tmp/supervisor/log
..rubystack-2.2.5-4/ruby/lib/ruby/gems/2.2.0/gems/fluentd-0.14.11-x86-mingw32/lib/fluent/supervisor.rb:329:in initialize'

I want to Fixes  My original issue. 
and Please show that fixes  are plenty of many other similar fixes on Windows .
I expect the ability of youres contributing to the ‘ruby projects‘.

Best reguards.

**Comment by cosmo0920** [comment] 2017-03-06 09:41
Hi, I couldn't reproduce this issue.

My environment

* Windows 10 Pro
* git from GitHub for Windows
* Fluentd master (c7281883dcfa16aceb5ef724aba8825902fa6e59)
* Ruby 2.3.1

---

Adding git into PATH in cmd:

```cmd
set PATH=C:\Users\<account name>\AppData\Local\GitHub\PortableGit_624c8416ee51e205b3f892d1d904e06e6f3c57c8\cmd\;%PATH%
```

And then,

```cmd
cmd> bundle exec ruby test\test_supervisor.rb
Loaded suite test/test_supervisor
Started
........O
========================================================================================================================
Windows cannot handle signals [test_main_process_signal_handlers(SupervisorTest)]
test/test_supervisor.rb:111:in `test_main_process_signal_handlers'
========================================================================================================================
.O
========================================================================================================================
Windows cannot handle signals [test_rpc_server(SupervisorTest)]
test/test_supervisor.rb:154:in `test_rpc_server'
========================================================================================================================
O
========================================================================================================================
Windows cannot handle signals [test_supervisor_signal_handler(SupervisorTest)]
test/test_supervisor.rb:133:in `test_supervisor_signal_handler'
========================================================================================================================
.

Finished in 10.070189 seconds.
------------------------------------------------------------------------------------------------------------------------
13 tests, 83 assertions, 0 failures, 0 errors, 0 pendings, 3 omissions, 0 notifications
100% passed
------------------------------------------------------------------------------------------------------------------------
1.29 tests/s, 8.24 assertions/s
```

**Comment by reversi-fun** [comment] 2017-03-09 04:23
I   can reproduced  by "ruby 2.3.3p222"

>> 
 -------------------------------------------
git
'git' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

>> 

>> 

bundle exec ruby test/test_supervisor.rb
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `fluentd.gemspec`: No such file or director
y - git ls-files. Bundler cannot continue.

   from fluentd/fluentd.gemspec:13
  
     gem.add_development_dependency("oj", ["~> 2.14"])
   end
   require File.expand_path('../lib/fluent/version', __FILE__)
. Bundler cannot continue.

   from fluentd/Gemfile:3
     instance_eval File.read(local_gemfile)
   end
   source 'https://rubygems.org/'
>

**Comment by cosmo0920** [comment] 2017-03-09 04:49
Hmm, this issue is caused by not found git in PATH.
But this issue may won't fix because there is a workaround. 
GitHub for Windows provides GitShell which adds git in PATH at startup.

**Comment by repeatedly** [comment] 2017-03-09 05:37
I added `Development` section for adding some basic informations: https://github.com/fluent/fluentd#development

**Closed** 2017-04-25 12:19 UTC
Labels: bug, v0.14, windows
