### ISSUE TITLE
Fluentd stuck.

### ISSUE THREAD

**Issue by sergeyarl** [fluent/fluentd#1889] opened 2018-03-12 22:03 UTC
Hi! 

We are using high availability scheme with multiple fluentd forwarders, that are running in docker containers and sending logs to active-backup fluentd aggregators pair. An aggregator node then saves logs to disk in text form and also sends a copy to Elasticsearch server. 

Every once in a while something happenes to active fluent aggregator and after that all forwarders start to respond very slowly. Sometimes it seems that they got stuck. Getting stats page `http://localhost:24220/api/plugins.json` takes about 1 minute. 

It is impossible to restart fluentd on aggregator nodes with service manager. In order to stop it I need to use `kill -9` command.  

After aggregator fluentd is restarted, forwarders start to behave normally. 

We use CentOS 7 x86_64 as an OS on all nodes.

On aggregator nodes fluentd is installed as td-agent rpm: td-agent-2.3.6-0.el7.x86_64.
On forwarder nodes we use official fluend docker images.

Forwarder config file:

```

<source>
  @type monitor_agent
  bind 127.0.0.1
  port 24220
</source>

# TCP input
<source>
  @type forward
  bind 127.0.0.1
  port 24224
</source>

# Logs Forwarding
<match **>
  @type forward

  heartbeat_type tcp
  send_timeout 60s
  recover_wait 10s
  heartbeat_interval 1s
  phi_threshold 16
  hard_timeout 120s

  <server>
    name logs1
    host logs1
    port 8889
    weight 60
  </server>

  <server>
    name logs2
    host logs2
    port 8889
    weight 60
    standby
  </server>

  flush_interval 10s

  buffer_type file
  buffer_path /fluentd/log/buffer/forward
  buffer_chunk_limit 4m
  buffer_queue_limit 4096

  num_threads 2

  expire_dns_cache 600
</match>
```

Sigdumps are attached.

[sigdump-forwarder.tar.gz](https://github.com/fluent/fluentd/files/1804720/sigdump-forwarder.tar.gz)
[sigdump-aggregator.tar.gz](https://github.com/fluent/fluentd/files/1804724/sigdump-aggregator.tar.gz)

Thank you! 

Regards,
Sergey

**Comment by sergeyarl** [comment] 2018-03-15 14:29
Hi! 

Any chances to figure out why this is happening? It is rather severe problem for us. Due to this thing we are not able to use fluentd in production any more :( 

Thanks. 

Regards,
Sergey

**Comment by toru-takahashi** [comment] 2018-03-15 14:41
You can monitor fluentd usage by following. 
https://docs.fluentd.org/v0.12/categories/monitoring
With it, You can see fluentd's buffer and other stats.
So, you can check the usage when fluentd stuck.

I often heard that Elasticsearch stuck to ingest data, then fluentd couldn't send data to elasticsearch, and it causes some issues.

In order to identify the cause, I recommend to remove elasticsearch output, and then try to reproduce the issue.

Thanks,

**Comment by sergeyarl** [comment] 2018-03-15 14:55
> I often heard that Elasticsearch stuck to ingest data, then fluentd couldn't send data to elasticsearch, and it causes some issues.

but if fluentd aggregator's inability to send data to elasticsearch causes fluentd forwarder to get stuck (even while providing stats when querying stats url http://localhost:24220/api/plugins.json ), then this is an obvious bug, isn't it? 

Like a chain reaction - elasticsearch server somehow fails (allegedly), that makes aggregator instance to get stuck, and after that a forwarder instances get stuck. We kill aggregator process, then start it again, and _all_ forwarder instances then start to work properly. 

Thanks for ` @type debug_agent` - i'll check it shortly. But it will be difficult to reproducte the problem - it happens once in a week or so, and also we temorrarily removed fluentd from production - this failure presumably caused other docker services to fail (we cannot say for sure though).  

Regards,
Sergey

**Comment by fujimotos** [comment] 2018-03-20 01:26
@sergeyarl 

FWIW, I think the forwarder side of your problem is fixed by  #1901.

So upgrade your forwarder to the latest version (v1.1.2) and see what happens.
Please report back the result here, so that we can confirm the fix is correct.

**Comment by toru-takahashi** [comment] 2018-03-20 07:31
Thank you!

**Comment by sergeyarl** [comment] 2018-04-04 13:06
@fujimotos i'm sorry, I'm still not able to test it, as I told, we temporarily switched from fluentd in production. Probably next week i'll have a chance. Thank you so much for the fix. I'll report once I have any info.

**Comment by sergeyarl** [comment] 2018-05-28 08:07
ok, after almost a month without issues it happened again. i attached aggregator and forwarder dumbs to the message. 

[fluentd-aggregator-28.05.tar.gz](https://github.com/fluent/fluentd/files/2044187/fluentd-aggregator-28.05.tar.gz)
[fluentd-forwarder-28-05.tar.gz](https://github.com/fluent/fluentd/files/2044188/fluentd-forwarder-28-05.tar.gz)

Can you please check.

Thanks! 

Regards,
Sergey

**Comment by fujimotos** [comment] 2018-05-28 08:55
> ok, after almost a month without issues it happened again.

If your problem is "the aggregator node is getting stuck", then you should upgrade it to Fluentd v1.1.3 too.

AFAICS, you are still using v0.14.21 for the aggregator. So I think upgrading the version should prevent the aggregator from getting overloaded (when Elasticsearch is down), which solves at least the half of your problem.

**Comment by sergeyarl** [comment] 2018-05-28 09:12
@fujimotos we're using td-agent on aggregators. so as I understand Fluentd v1.1.3 is td-agent3, right?

**Comment by fujimotos** [comment] 2018-05-28 09:34
> So I assume there is no Fluentd v1.1.3 in the rpm repo, right?

No, it is not available yet.

AFAICT,  the new release of td-agent (which contains Fluentd v1.1.3) is being prepared
right now. See https://github.com/treasure-data/omnibus-td-agent/pull/173 for the progress.

So you need to wait a little to upgrade the node...

**Comment by sergeyarl** [comment] 2018-05-28 09:48
@fujimotos I see. thanks!

**Comment by ganmacs** [comment] 2019-12-23 03:50
seems to be solved. if you have another error, feel free to notify us.

**Closed by ganmacs** 2019-12-23 03:50 UTC
