### ISSUE TITLE
After a file rotation, in_tail will write log lines in new log file before the log lines in the rotated log file

### ISSUE THREAD

**Issue by tomfitzhenry** [fluent/fluentd#1055] opened 2016-06-16 16:51 UTC
- fluentd or td-agent version.
  td-agent-2.3.0-0.el7.x86_64
- Environment information, e.g. OS.
  Linux i-03864a911aa975c3a 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Your configuration

```
<source>
  type tail
  format none
  path /var/log/foo/output.log
  pos_file /var/log/td-agent/application-log_foo.pos
  read_from_head true
  tag application-log
</source>

<match application-log>
    type s3
    s3_bucket foobarbucket
    s3_region eu-west-1
    path logs/annotator/application-log/
    buffer_path /var/log/td-agent/buffer/s3-application-log
    time_slice_format %Y-%m-%d/%{hostname}/%Y-%m-%dT%H_%{hostname}
    flush_interval 600s
    buffer_chunk_limit 64m
    format single_value
    store_as gzip
    num_threads 1
    use_server_side_encryption AES256

    <instance_profile_credentials>
    </instance_profile_credentials>
</match>
```
- Your problem explanation. If you have an error logs, write it together.
## Steps to reproduce

```
$ killall -STOP ruby # to more easily create this race condition
$ echo foo >> /var/log/foo/output.log
$ mv /var/log/foo/output.log /var/log/foo/output.log.0 # to simulate a log rotation
$ echo bar >> /var/log/foo/output.log
$ killall -CONT ruby
$ sleep 5 # to give td-agent time to do its thing
$ cat /var/log/td-agent/buffer/s3-application-log*
```
## Expected

```
foo
bar
```
## Actual

```
bar
foo
```
## Output of `/var/log/td-agent/td-agent.log`

```
2016-06-16 16:46:36 +0000 [info]: detected rotation of /var/log/foo/output.log; waiting 5 seconds
2016-06-16 16:46:36 +0000 [info]: following tail of /var/log/foo/output.log
```

**Comment by repeatedly** [comment] 2016-06-17 03:21
Thanks for the reporting.
I will check it later.

**Comment by repeatedly** [comment] 2016-07-07 22:53
I confirmed this behaviour.
I will check the code.

**Comment by tagomoris** [comment] 2016-11-17 07:03
@repeatedly are there any progress?

**Comment by repeatedly** [comment] 2016-11-17 10:57
I confirmed the behaviour but I can't find the cause why SIGSTOP/SIGCONT changes IO order.
I need deep knowledage about signal and IO scheduling to debug it.
But it need long time so I'm pending it...

**Comment by repeatedly** [comment] 2018-03-10 01:43
Fixed by https://github.com/fluent/fluentd/pull/1880

**Closed by repeatedly** 2018-03-10 01:43 UTC
Labels: bug
