### ISSUE TITLE
Duplicating Logs were occurred when td-agent is stoped.

### ISSUE THREAD

**Issue by takeo-hidaka** [fluent/fluentd#3137] opened 2020-09-28 16:09 UTC
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**

Duplicating Logs were occurred when td-agent is stoped.

We consider that the buffer files which is created by `flush_at_shutdown true` within `out forward plugin` has not deleted even if the td-agent is stopped.
Thus, it seems to be caused log duplicating by retransmitting when td-agent starts.

**To Reproduce**
* Prepare 2 hosts; one is a sender and the other is a receiver.
* We intended to be aggregated to the receiver the nginx access logs which the sender has.
* * The log has a unique ID that the receiver is able to check for duplicates.
* * The outbound logs toward the receiver is  1 per sec.
* When the logs are fighting,  the sender's td-agent process is stop.
* After 5 sec from the stopping the process, we restarted the sender's td-agent process to continue aggregation. 
* When we confirm the logs whether duplicating or not on the receiver.
* Against expectations, there are some couple of logs which have a same unique ID.

With v0.12,  we never encountered data duplications above the procedure, Although  updating 1.11.1 , we always encountered it. 
Reloading the td-agent also indicates to cause the same behavior.

**Expected behavior**

I suppose the buffer file can be deleted if its contents has been already sent.
As `flush_at_shutdown` is true, the remaining data in the buffer file should have been already sent to the receiver before td-agent process stops.

**Your Environment**

- Fluentd or td-agent version: td-agent 1.11.1 
- Operating system: Ubuntu 18.04.2 LTS (Bionic Beaver)
- Kernel version: 4.15.0-55-generic

**Your Configuration**

*** for the host of sender side. 

```
<source>
  @type tail
  @id input_tail
  <parse>
    @type nginx
  </parse>
  path /var/log/nginx/access.log
  tag td.nginx.access
</source>

<match td.*.*>
  @type copy
  @id output_copy
  <store>
    @type forward
    require_ack_response true
    transport tcp
    heartbeat_interval 5
    phi_threshold 5
    send_timeout 60
    hard_timeout 60
    <buffer>
      @type file
      path /var/log/td-agent/buffer/td
      chunk_limit_size 16m
      queue_limt_length 512
      flush_thread_count 4
      flush_interval 1s
      retry_max_times 60
      retry_max_interval 10s
      flush_at_shutdown true
    </buffer>
    <server>
       host 192.168.86.102
       port 8889
    </server>
  </store>
  <store>
    @type file
    path /var/log/td-agent/td-%Y-%m-%d/%H.log
  </store>
</match>
```

for the host of receiver side.

```
<source>
  @type forward
  bind 0.0.0.0
  port 8889
  tag wow
</source>

<match wow.**>
  @type copy
  <store>
    type file
    path /var/log/td-agent/out
    time_slice_format %Y%m%d%H
  </store>
</match>

```
**Your Error Log**

#### sender side : after stopping td-agent.  

this buffer file contains a string of unix time "1599639024".

```
vagrant@ubuntu-bionic:/var/log/td-agent/buffer/td$ sudo service td-agent start
vagrant@ubuntu-bionic:/var/log/td-agent/buffer/td$ sudo service td-agent stop
vagrant@ubuntu-bionic:/var/log/td-agent/buffer/td$ for _f in `ls -1 *.log*`; do echo "=====";echo $_f; echo "";cat $_f; echo ""; done
=====
buffer.q5aedcfbd340ec9df1785594f51dd83c5.log

....
/?1599639024
curl/7.58.0
...

=====
buffer.q5aedcfbd340ec9df1785594f51dd83c5.log.meta

... 
vagrant@ubuntu-bionic:/var/log/td-agent/buffer/td$
```

#### receiver side : before stopping td-agent on the sender side.

The data with '1599639024' have been already received.

```
vagrant@ubuntu-bionic:/var/log/td-agent/out$ for _FILE in `ls -1 *.log`; do echo $_FILE;ls -l $_FILE;echo "";echo "tail =====";tail -n 3 $_FILE;echo "";echo "diff =====";diff <(cat $_FILE) <(cat $_FILE|uniq)  ; done
buffer.b5aedceb6aa7801a36be087ddfb6fe294.log
-rw-r--r-- 1 td-agent td-agent 2784 Sep  9 08:10 buffer.b5aedceb6aa7801a36be087ddfb6fe294.log

tail =====
2020-09-09T08:10:22+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639022","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}
2020-09-09T08:10:23+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639023","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}
2020-09-09T08:10:24+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639024","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}

diff =====
vagrant@ubuntu-bionic:/var/log/td-agent/out$
```

#### receiver side : after stopping td-agent on the sender side.

the data with '1599639024' found twice.

```
vagrant@ubuntu-bionic:/var/log/td-agent/out$ for _FILE in `ls -1 *.log`; do echo $_FILE;ls -l $_FILE;echo "";echo "tail =====";tail -n 3 $_FILE;echo "";echo "diff =====";diff <(cat $_FILE) <(cat $_FILE|uniq)  ; done
buffer.b5aedceb6aa7801a36be087ddfb6fe294.log
-rw-r--r-- 1 td-agent td-agent 4176 Sep  9 08:15 buffer.b5aedceb6aa7801a36be087ddfb6fe294.log

tail =====
2020-09-09T08:15:32+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639332","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}
2020-09-09T08:15:33+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639333","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}
2020-09-09T08:15:34+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639334","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}

diff =====
17d16
< 2020-09-09T08:10:24+00:00    wow    {"remote":"127.0.0.1","host":"-","user":"-","method":"GET","path":"/?1599639024","code":"200","size":"612","referer":"-","agent":"curl/7.58.0"}
vagrant@ubuntu-bionic:/var/log/td-agent/out$

```

**Additional context**

**Comment by bryanstephens** [comment] 2020-11-20 23:53
We also experienced log duplication sent to BigQuery, possibly due to this issue.

<details>
<summary>
A configuration example:
</summary>

```

<source>
  @type tail
  path /var/log/reception.log
  tag receptionlog.bq
  pos_file /var/log/td-agent/receptionlog-bq.pos
  read_from_head true
  <parse>
    @type regexp
    expression /(?<message>.*)/
  </parse>
</source>

<filter receptionlog.bq>
  @type grep
  <regexp>
    key message
    pattern /.*/
  </regexp>
</filter>

<filter receptionlog.bq>
  @type parser
  key_name message
  emit_invalid_record_to_error false
  <parse>
    @type regexp
    expression /(?<date>[^\s]+)(\s+)\@(?<message_id>[^\@]*)...shortened to reduce noise...$/m
  </parse>
</filter>

<match receptionlog.bq>
  @type bigquery_load
  <buffer>
    @type file
    path /var/log/td-agent/receptionlog.buffer
    flush_at_shutdown true
    timekey_use_utc
    total_limit_size 1g
    flush_interval 3600
  </buffer>

  # Authenticate with BigQuery using the VM's service account.
  auth_method compute_engine
  project projectid
  dataset fluentd
  table receptionlog
  fetch_schema true
  ignore_unknown_values true
  max_bad_records 50
  <inject>
    # Convert fluentd timestamp into TIMESTAMP string
    time_key date
    time_type string
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    utc true
  </inject>
</match>

```

</details>

<details>
<summary>
Logs at shutdown:
</summary>

```

2020-11-17 17:25:20 -0500 [info]: Received graceful stop
2020-11-17 17:25:20 -0500 [info]: Received graceful stop
2020-11-17 17:25:21 -0500 [info]: #0 fluentd worker is now stopping worker=0
2020-11-17 17:25:21 -0500 [info]: #0 shutting down fluentd worker worker=0
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a4a9bb0"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:forward plugin_id="object:3fd22a719508"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:monitor_agent plugin_id="object:3fd22a7d2a94"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22bf6231c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a46c670"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a49d018"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a43f7b0"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a4520a4"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a460c1c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a47b198"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a487f38"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:tail plugin_id="object:3fd22a4908a4"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down input plugin type=:http plugin_id="object:3fd22b31ff3c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22aac7cf4"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22bf59988"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:logsize plugin_id="object:3fd22bf62a38"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:parser plugin_id="object:3fd22c06eb34"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:grep plugin_id="object:3fd22aa292fc"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:grep plugin_id="object:3fd22aa6994c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:parser plugin_id="object:3fd22aa70b5c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:truncate_field plugin_id="object:3fd22aa9ed90"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22aaa2a94"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22aab7f48"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:logsize plugin_id="object:3fd22aab3588"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:logsize plugin_id="object:3fd22aac33e8"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:logsize plugin_id="object:3fd22c05d938"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22c353aac"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:grep plugin_id="object:3fd22c0ee500"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:parser plugin_id="object:3fd22aa308b8"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22aa58e1c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:3fd22aa1813c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22f1ccba4"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22aab601c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22aaa6770"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22bf5507c"
2020-11-17 17:25:21 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22aacbf5c"
2020-11-17 17:25:22 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22af97590"
2020-11-17 17:25:22 -0500 [info]: #0 shutting down output plugin type=:newrelic plugin_id="object:3fd22aa5cb98"
2020-11-17 17:25:26 -0500 [info]: #0 shutting down output plugin type=:bigquery_load plugin_id="object:3fd22bf151fc"
2020-11-17 17:25:26 -0500 [info]: #0 shutting down output plugin type=:bigquery_load plugin_id="object:3fd22aa3d180"
2020-11-17 17:25:26 -0500 [info]: #0 shutting down output plugin type=:bigquery_load plugin_id="object:3fd22aa7f0f8"
2020-11-17 17:25:26 -0500 [info]: #0 delayed commit for buffer chunks was cancelled in shutdown chunk_id="5b45451d003d3ac2f920bed878e08d19"
2020-11-17 17:25:26 -0500 [info]: #0 delayed commit for buffer chunks was cancelled in shutdown chunk_id="5b4541766301a4129548fd2ba9c887cd"
2020-11-17 17:25:26 -0500 [info]: #0 delayed commit for buffer chunks was cancelled in shutdown chunk_id="5b45451d01ad3b6d014cd19d5923d486"
2020-11-17 17:25:26 -0500 [info]: Worker 0 finished with status 0

```

</details>

**Comment by agup006** [comment] 2021-01-29 01:58
@cosmo0920 is this an issue you would be able to take a look at?

**Comment by cosmo0920** [comment] 2021-01-29 05:33
@kenhys Could you take a glance in this issue?

**Comment by kenhys** [comment] 2021-02-01 03:34
I can reproduce it with 1.12.0.

**Comment by kenhys** [comment] 2021-02-01 04:57
When this issue occurs, 

* sender store @file log is matched with receiver side
* sender buffer still keep already sent log after shutting down
* when fluentd is restarted, the remained buffer is sent, it causes duplicating logs

**Comment by kenhys** [comment] 2021-02-02 07:25
Digging furthermore, it seems that `force_flush` and `submit_flush_all` are called .
https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/output.rb#L495

**Comment by kenhys** [comment] 2021-02-09 01:06
FYI: Why PluginHelper::Thread::stop and after_shutdown are different slightly?
https://groups.google.com/g/fluentd/c/6TkJJ0PrCF4

It may be related to this issue.

**Comment by kenhys** [comment] 2021-02-09 01:23
```ruby
diff --git a/lib/fluent/plugin_helper/thread.rb b/lib/fluent/plugin_helper/thread.rb
index 8d725ae5..964920ea 100644
--- a/lib/fluent/plugin_helper/thread.rb
+++ b/lib/fluent/plugin_helper/thread.rb
@@ -142,6 +142,7 @@ module Fluent
         wakeup_threads = []
         @_threads_mutex.synchronize do
           @_threads.each_value do |thread|
+            thread[:_fluentd_plugin_helper_thread_running] = false
             wakeup_threads << thread if thread.alive? && thread.status == "sleep"
           end
         end
```

It seems that the above patch will solve. but there may be a side effect.

**Comment by yugo-horie** [comment] 2021-02-09 08:29
Hi, @kenhys 
Now I tackle to be resolving this issue with @takeo-hidaka. 

> FYI: Why PluginHelper::Thread::stop and after_shutdown are different slightly?
> https://groups.google.com/g/fluentd/c/6TkJJ0PrCF4

At first I have to apologize for my faults. I had submitted above the question not using public accounts.

For this issue, the most important fact is that `out_forward _receiving_ack` thread have stopped faster than the entering ` shutdown phase`. 
We found that the reading the ack has stopped at the `stop phase` nevertheless it had continued the flush threads to send the chunks. Therefore, it cannot read ack which replied after `shutdown phase`, it is regarded the chunks lost. And occurring the retransmit.
After all, we are applying the follow patch, 
In this patch's points 
- To indicates the ack at first `after_shutdown phase` in out_forward at last
- Suspend the `try_flush` at `shutdown phase` in output 

```
diff --git a/out_forward.rb b/out_forward.rb
index 0474e46..c010d9b 100644
--- a/out_forward.rb
+++ b/out_forward.rb
@@ -346,6 +346,39 @@ module Fluent::Plugin
       end
     end

+    def after_shutdown
+      last_ack
+      super
+    end
+    def last_ack
+      select_interval = if @delayed_commit_timeout > 3
+                          1
+                        else
+                          @delayed_commit_timeout / 3.0
+                        end
+
+      @ack_handler.collect_response(select_interval) do |chunk_id, node, sock, result|
+        @connection_manager.close(sock)
+
+        case result
+        when AckHandler::Result::SUCCESS
+          commit_write(chunk_id)
+        when AckHandler::Result::FAILED
+          node.disable!
+          rollback_write(chunk_id, update_retry: false)
+        when AckHandler::Result::CHUNKID_UNMATCHED
+          rollback_write(chunk_id, update_retry: false)
+        else
+          log.warn("BUG: invalid status #{result} #{chunk_id}")
+
+          if chunk_id
+            rollback_write(chunk_id, update_retry: false)
+          end
+        end
+      end
+    end
+
```
Above the patch, while  it's quite dirty for me. 
But it would be good if it reused `ack_reader` without `while thread_current_running?`.
Could you have any ideas more clear?

```
diff --git a/output.rb b/output.rb
index b5128bc..f41fd10 100644
--- a/output.rb
+++ b/output.rb
@@ -188,6 +188,7 @@ module Fluent
         @rollback_count = 0
         @flush_time_count = 0
         @slow_flush_count = 0
+        @suspend_flush = false

         # How to process events is decided here at once, but it will be decided in delayed way on #configure & #start
         if implement?(:synchronous)
@@ -508,6 +509,7 @@ module Fluent
       def shutdown
         @secondary.shutdown if @secondary
         @buffer.shutdown if @buffering && @buffer
+        @suspend_flush = true

         super
       end
@@ -1435,6 +1437,11 @@ module Fluent
               interval = next_retry_time.to_f - Time.now.to_f
             else
               state.mutex.unlock
+             if @suspend_flush
+               state.mutex.lock
+                state.cond_var.wait(state.mutex, interval) if interval > 0
+               next
+             end
               begin
                 try_flush
                 # next_flush_time uses flush_thread_interval or flush_thread_burst_interval (or retrying)
```

**Comment by repeatedly** [comment] 2021-02-17 23:43
Changing output behavior affects lots of plugins.
So I think following step is better

1. Apply former patch to out_forward first
2. Check current lifecycle behavior about `shutdown`/`stop` and more.
3. Write proper patch for this

**Comment by yugo-horie** [comment] 2021-02-25 04:14
@repeatedly 
We're able to change only out_forward plugin behavior.

**Closed** 2021-03-08 00:21 UTC
