### ISSUE TITLE
fluentd don't send parsed json logs to elastic

### ISSUE THREAD

**Issue by shmykyta** [fluent/fluentd#2238] opened 2018-12-18 11:15 UTC
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd version - from docker hub fluent/fluentd:v1.3-debian 
- Docker container on 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

- Your configuration
fluent.conf 

```
<source>
  @type tail
  path "/etc/fluent/log/*/*-json.log"
  pos_file "/etc/fluent/pos/fluent-docker.pos"
  time_format %Y-%m-%dT%H:%M:%S
  tag "docker.*"
  format json
</source>

<source>
  @type tail
  path "/etc/fluent/syslog/syslog"
  pos_file "/etc/fluent/pos/fluent-syslog.pos"
  tag syslog
  <parse>
    @type multi_format
    <pattern>
      format regexp
      expression \A^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-z]*) ?(?:[^\:]*\:)? (?:\[(?<pid>[a-zA-Z0-9_\/\.\-]+)\]) *(?<message>.*)$
    </pattern>
    <pattern>
      format regexp
      expression \A^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</source>

<filter docker.etc.fluent.log.*.*.log>
  @type docker_metadata
</filter>

<filter docker.**>
  @type record_transformer
  <record>
    log_type docker
    hostname_tru "#{Socket.gethostname}"
    environment "#{ENV['HOSTNAME_NODE']}"
  </record>
</filter>

<filter syslog.**>
  @type record_transformer
  <record>
    log_type syslog
    hostname_tru "#{Socket.gethostname}"
    environment "#{ENV['HOSTNAME_NODE']}"
  </record>
</filter>

### TO DO REGEXP ###

<match docker.**>
  @type rewrite_tag_filter
  <rule>
    key $['attrs']['tag']
    pattern ^(.+)$
    tag sorted.$1
  </rule>
</match>

<filter sorted.platform_nginx_1>
  @type parser
  key_name log
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</filter>

<match **>
  @type elasticsearch
  host elasticsearch
  port 9200
  buffer_queue_limit 512m
  disable_retry_limit false
  retry_limit 5
  buffer_chunk_limit 5m
  include_tag_key true  
  logstash_prefix "fluentd"
  logstash_dateformat "%Y%m%d"
  tag_key "log_path"
  index_name "fluentd-%Y-%m-%d" 
  logstash_format true
  flush_interval 5s
  max_retry_wait 300s # ~5 minutes
  retry_limit 300
</match>
```
- Your problem explanation. If you have an error logs, write it together.

So i had logs from my docker containers in json format, then i route it and want to parse in unique rules.
For example my nginx wrote logs in json format and its in field log
example of nginx log above:
```
{ "time": "XXX", "remote_addr": "XXX", "request_uri": "XXX", "request_method": "GET", "status": "200", "body_bytes_sent": "48043", "http_referer": "-", "http_host": "XXX", "geoip_country_code": "XXX", "geoip_city": "-", "request_length": "1245", "request_time": "0.203", "upstream_header_time": "0.196", "upstream_connect_time": "0.000", "upstream_status": "200", "upstream_response_time": "0.204", "upstream_addr": "XXX", "service": "XXX", "http_user_agent": "XXX" }
```
But parser json don't parse it and logs missed, fluentd dont sent it to elastic, idk but i can't find it in elastic
```
<filter sorted.platform_nginx_1>
  @type parser
  key_name log
  <parse>
    @type multi_format
    <pattern>
      format json
    </pattern>
    <pattern>
      format none
    </pattern>
  </parse>
</filter>
```
that part in my config don't work at all

also provide initial log from fluentd, there are no warnings in log:
```
2018-12-18 16:22:40 +0000 [info]: starting fluentd-1.3.0 pid=8 ruby="2.3.3"
2018-12-18 16:22:40 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/usr/local/bin/fluentd", "-c", "/etc/fluent/fluent.conf", "--under-supervisor"]
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-concat' version '2.3.0'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.3'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.12.5'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-grep' version '0.3.4'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-grok-parser' version '2.4.0'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2018-12-18 16:22:40 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2018-12-18 16:22:40 +0000 [info]: gem 'fluentd' version '1.3.0'
``` 

Trying to check in debug mode with -vv but nothing it fluentd logs 
Any ideas why fluentd don't parse json in log ? 
thanks

**Comment by okkez** [comment] 2018-12-20 01:59
I've tested following config:

```
<source>
  @type dummy
  dummy [
    {"log": "{ \"time\": \"XXX\", \"remote_addr\": \"XXX\", \"request_uri\": \"XXX\", \"request_method\": \"GET\", \"status\": \"200\", \"body_bytes_sent\": \"48043\", \"http_referer\": \"-\", \"http_host\": \"XXX\", \"geoip_country_code\": \"XXX\", \"geoip_city\": \"-\", \"request_length\": \"1245\", \"request_time\": \"0.203\", \"upstream_header_time\": \"0.196\", \"upstream_connect_time\": \"0.000\", \"upstream_status\": \"200\", \"upstream_response_time\": \"0.204\", \"upstream_addr\": \"XXX\", \"service\": \"XXX\", \"http_user_agent\": \"XXX\" }"}
  ]
  tag dummy
</source>

<filter dummy>
  @type parser
  key_name log
  <parse>
    @type json
  </parse>
</filter>

<match dummy>
  @type stdout
</match>
```

This can parse the log as JSON.

You must use label feature to apply `<filter>` directive after `<match>` directive like following:

```
<source>
  # snip
  @label @INPUT
</source>

<label @INPUT>
  <filter>
    @type parser
    # snip
  </filter>
  <match>
    @type rewrite_tag_filter
    <rule>
      key $['attrs']['tag']
      pattern ^(.+)$
      tag sorted.$1
    </rule>
    @label @NGINX
  </match>
</label>

<label @NGINX>
   <filter>
    @type parser
    # snip
   </filter>
   <match>
     @type relabel
     @label @OUTPUT
   </match>
<label>

<label @OUTPUT>
  <match>
    @type elasticsearch
    # snip
  </match>
</label>
```

BTW, this does not follow [the guidline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md). Closing.

**Closed by okkez** 2018-12-20 01:59 UTC

**Comment by repeatedly** [comment] 2018-12-20 02:39
I assume the problem is no `$['attrs']['tag']` field in the logs.
Yeah, please post it on mailing list after re-check your configuration and log format.
