### ISSUE TITLE
[error]: #0 unexpected error on reading data host="192.168.16.9" port=64283 error_class=NoMethodError error="undefined method `empty?' for nil:NilClass"

### ISSUE THREAD

**Issue by felixzh2020** [fluent/fluentd#1973] opened 2018-05-07 08:42 UTC
```aconf
# built-in TCP input
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# Kafka buffered output
<match **>
  @type kafka_buffered
  
  brokers       192.168.16.8:9092

  buffer_type   file
  buffer_path   /var/log/fluent/buffer-01/*.buffer
 
  flush_interval 10s
  buffer_chunk_limit 8m
  buffer_queue_limit 3600

  retry_wait          1s
  max_retry_wait      60s
  disable_retry_limit true

  # ruby-kafka producer options
  max_send_retries    1
  required_acks       1
  compression_codec   gzip
  output_data_type json
  output_include_time true
  num_threads   3
</match>

<system>
  # loglevel: trace, debug, info, warn, error
  log_level trace
</system>
```

This error lead to error, as follow:
emit transaction failed: error_class=NoMethodError error="undefined method `empty?' for nil:NilClass" tag="json.test"

**Comment by felixzh2015** [comment] 2018-05-07 08:48
The error's position is /fluentd-1.1.3/lib/fluent/plugin/buffer.rb:544:in `write_once'
![image](https://user-images.githubusercontent.com/16359007/39693370-5fb5f2d2-5216-11e8-8f4d-f68b9610817f.png)

**Comment by felixzh2015** [comment] 2018-05-07 08:55
Fluentd send its debug log, also exists this error:
[warn]: #0 emit transaction failed: error_class=NoMethodError error="undefined method `empty?' for nil:NilClass" tag="fluent.trace"

**Comment by jl2005** [comment] 2018-05-18 05:27
I have same issue.

**Comment by repeatedly** [comment] 2018-05-23 09:03
@felixzh2015 Could you show the reproducible step?
I tested your configuration with v1.2.0 but no above error happen.

**Comment by felixzh2015** [comment] 2018-05-25 01:53
This can't always happen. You need to run for a long time.
I use fluent-logger-java.

**Comment by gangseok514** [comment] 2018-10-15 01:00
I have same issue in v1.2.1

emit transaction failed: error_class=NoMethodError error="undefined method `empty?' for nil:NilClass" location="/var/lib/gems/2.3.0/gems/fluentd-1.2.1/lib/fluent/plugin/buffer.rb:544:in `write_once'

**Comment by cosmo0920** [comment] 2021-03-17 06:04
I'm trying to reproduce this issue, but I couldn't reproduce....

**Comment by felixzh2020** [comment] 2021-03-27 03:32
This can't always happen. You need to run for a long time. You need to send big data

**Comment by daipom** [comment] 2023-04-10 06:24
We know that such an error occurs when a chunk file is corrupted due to an abnormal outage, etc.
We are working on improving the feature for chunk file corruption in this issue.

* #3970

So I close this issue now, but if you are still experiencing these errors even though an abnormal outage doesn't occur, please contact us.

**Closed by daipom** 2023-04-10 06:24 UTC
Labels: bug
