### ISSUE TITLE
Fail to Flush Buffer 

### ISSUE THREAD

**Issue by prabinsubedi** [fluent/fluentd#819] opened 2016-03-02 09:45 UTC
2016-03-02 09:42:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-02 10:00:53 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"localhost\", :port=>9200, :scheme=>\"http\"})! Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)" plugin_id="object:3fbb5fbe4290"

OS : ubuntu 14.04

**Comment by repeatedly** [comment] 2016-03-02 12:09
> 2016-03-02 09:42:43 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-02 10:00:53 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"localhost\", :port=>9200, :scheme=>\"http\"})! Connection refused - connect(2) for 127.0.0.1:9200 (Errno::ECONNREFUSED)" plugin_id="object:3fbb5fbe4290"

This say the cause. fluent-plugin-elasticsearch can't reach elasticsearch server.
This is not a bug of fleutnd so close this issue.

**Closed by repeatedly** 2016-03-02 12:09 UTC

**Comment by repeatedly** [comment] 2016-03-02 12:15
You should check elasticsearch, fluentd or your network setting.
